### ISSUE TITLE
Chaining eventually have property

### ISSUE THREAD

**Issue by mparpaillon** [domenic/chai-as-promised#100]
I'm trying to chain some tests with chai-as-promised without success.
I can't find in the documentation a proper example for this case.

Here is my test

```js
it('should be blablabla', function() {
    var request = xhr.get('http://www.my-mock.com/ok/200');

    return request.should.eventually
                     .be.fulfilled
                     .and.be.an('object')
                     .and.have.property('status', 200)
                     .and.have.property('data')
                     .and.have.deep.property('data.content');
});
```

But I get this error

```
AssertionError: expected 200 to have a property 'data'
```

What's the right way to write this test please ?
What am I doing wrong ?

Thanks

**Comment by mparpaillon** [comment]
Ok that's my problem

> Furthermore, property changes the subject of the assertion to be the value of that property from the original object. This permits for further chainable assertions on that property.

How can I test multi properties without changing the subject of the assertion then ?

**Comment by domenic** [comment]
Use multiple assertions?

This seems like a general Chai question, not specific to Chai as Promised.

**Comment by mparpaillon** [comment]
Well, since I can chain everything else I thought there would be a way to do it with chai-as-promised too.

So something like

```js
it('should be blablabla', function() {
    var request = xhr.get('http://www.my-mock.com/ok/200');

    return request.should.eventually.be.fulfilled 
        && request.should.eventually.be.an('object')
        && request.should.eventually.have.property('status', 200)
        && request.should.eventually.have.deep.property('data.content');
});
```

That's kinda ugly

**Comment by domenic** [comment]
You can't use && on promises, all promises are truthy. You need to use `Promise.all`.

**Comment by mparpaillon** [comment]
So this would be the recommended way to do this ?

```js
it('should be blablabla', function() {
    var request = xhr.get('http://www.my-mock.com/ok/200');

    return Promise.all([
        request.should.eventually.be.fulfilled,
        request.should.eventually.be.an('object'),
        request.should.eventually.have.property('status', 200),
        request.should.eventually.have.deep.property('data.content')
    });
});
```

I just want to follow the best practices of chai-as-promised here.

Thanks

**Comment by domenic** [comment]
Yeah, that should do the trick :)

**Comment by mparpaillon** [comment]
Thanks you
And thank you for chai-as-promised, it's great
