### ISSUE TITLE
Should `.eventually.throw()` treated the same way as `.be.rejected`?

### ISSUE THREAD

**Issue by krnlde** [domenic/chai-as-promised#103]
I recently had an issue testing an ES7 `async function`. Because I tried  `asyncFunction(falseParam).should.eventually.throw(Error)`. Having this discussion in mind chaijs/chai#415 we solved the problem by replacing `.eventually.throw()` with `.be.rejectedWith(Error)`. Since `async function`s have a synchronous looking code and you can actually `throw` from them, but on the outside provide a Promise, that wasn't clear to me in the first place. Docs also only suggest to `try { await asyncFunction(falseParam); } catch (e) { /* ... */ }` instead of alternatively `asyncFunction(falseParam).catch(handler)`.

Considering this use case, does it make sense to have the `.eventually.throw()` treated the same way as `.be.rejected`?

**Comment by domenic** [comment]
No.

**Comment by krnlde** [comment]
Wow. You didn't even bother an explanation. I just wanted to contributed. Sorry man.

**Comment by W3Max** [comment]
humm... that was harsh!? 8-|

**Comment by cyberwombat** [comment]
An explanation would be nice especially since the docs seem to imply they are similar:
    
    return promise.should.be.rejectedWith(Error); // other variants of Chai's `throw` assertion work too.

**Comment by domenic** [comment]
eventually.throw, like every other . eventually, means "apply the assertion to the eventual value". It only makes sense if the eventual value is a function.

This is completely different from .rejectedWith.

**Comment by cyberwombat** [comment]
Thank you though I am a little unclear still. My function returns a promise that can throw an error. Your comment seems to imply that eventually.throw should work?

    const p = somefnthatreturnsapromise()  // i.e. throw new Error('Foo')
    return expect(p).to.eventually.throw('foo') // Doesnt work - error just dumps to console
    return expect(p).to.eventually.be.rejectedWith('foo') // works
    return expect(p).to.be.rejectedWith('foo') // works as well

**Comment by domenic** [comment]
Promises cannot throw errors. You can have a promise that is fulfilled with a function that throws an error, although that is probably very rare, and I don't believe is what you are doing.

**Comment by cyberwombat** [comment]
I see. But then in what situation would `to.eventually.throw` work?

**Comment by domenic** [comment]
Like I said, when the promise is fulfilled with a function and you want to test what error that function throws.

**Comment by cyberwombat** [comment]
Ah. I get it now. Thanks for taking the time!

**Comment by FuzzySockets** [comment]
I have a very simple use case relating to this, and none of the above solutions seem to work.  Perhaps one of you could shed some light on why this simple use case isn't working?

`
export async function submitForm(values, dispatch) {
  try {
      throw new Error();
  } catch (e) {
      console.log(e);
  }
}
`

I naively thought .to.eventually.throw() would be the solution, but I see now from above it's not.  I also tried the aforementioned return expect(promise).to.eventually.be.rejectedWith(Error) but instead I get the AssertionError "expected promise to be rejected with 'Error' but it was fulfilled with undefined"

**Comment by domenic** [comment]
Your function never rejects, since you catch the error. There's no way to test the behavior of a function's internals that way.

**Comment by FuzzySockets** [comment]
@domenic That explains it.  Thank you!

**Comment by FuzzySockets** [comment]
There is a way to test the internals though, even without rejecting.  I can just create a sinon stub for console.log and ensure it's called with the correct error.  This isn't the final version of the method anywho, was just trying to wrap my head around chai-as-promised :)  Thanks again.
