### ISSUE TITLE
`assert.eventually.throws` doesn't seem to work

### ISSUE THREAD

**Issue by jonathanj** [domenic/chai-as-promised#104]
Using Mocha and Bluebird (although looking at the code I suspect this doesn't matter), I'm trying to assert that a promise is rejected using the assert-style:

```javascript
describe('a_promise', function() {
  it('asserts rejected', function() {
    let p = Promise.reject(new Error('Nope'));
    return assert.eventually.throws(p, Error, 'Nope');
  });
});
```

The result appears as though the rejected promise was simply returned from the test and no assertion took place. I suspect there may have to be a specialised method for this since the signature of `assert.throws` doesn't make much sense in the context of promises.

**Comment by domenic** [comment]
Look in the readme under "And there are, of course, promise-specific extensions:".

eventually.throws makes sense when you have a promise for a function and want to know whether that function throws or not.
