### ISSUE TITLE
[Question] expect on different object than the promise 

### ISSUE THREAD

**Issue by matanshukry** [domenic/chai-as-promised#112]
I couldn't find anyway to expect (or should or assert, even though I'm personally using expect) on a different object other than the promise, once a promise is fulled. If I'm using regular expect() inside .then(), they will not be passed correctly (when false) to done() method (mocha)

Example:

##### Method 1: put expect() calls inside .then()
Problem: does not notify done if the inner expect() calls are false

```
var data1;
expect(...then(function(data2, data3) {
  expect(data1).to.equal(0);
  expect(data3).to.equal(5);
  expect(data3).to.equal(5);
})).to.be.fulfilled.and.notify(done)
```

##### Method 2: Return array with expectable content, and expect on the array
Problem:
 - How can one check on items of the array, returned from .then()?
 - Even if it is possible, will the result message be informative and correct, if it will fail?
   that is, will the error context object be 'data1'(correct), or the array it self (wrong) ?

```
var data1;
expect(...then(function(data2, data3) {
  return [data1, data2, data3];
}).to.be.fulfilled.and
  /* Doesn't exists, obviouslly; */
  .expect[0].to.equal(2)
  .and.expect[1].to.equal(5)
```

##### Method 3: Check data regardless of promise
Problem: How can one check on data that is not the promise, but only after the promise is fulfilled?

```
var data1;
expect(...then(function() { })).to.be.fulfilled.and
   /* Doesn't exists, obviouslly */
   .expect(data1).to.equal(2)
```

**Comment by domenic** [comment]
< `expect(...then(function(data2, data3) {`

What is this supposed to do?

**Comment by matanshukry** [comment]
it is a notation, where "..." is some irrelevant code that result in a promise (hence .then call on it).

same as:
```
expect(Promise.resolve([1, 5]).then(function (arr) {
```

Many of the code I've written is irrelevant, and only there to describe the issue; Which is, how can you check arbitrary variables, only once a promise is finished.

p.s.
Currently, I'm doing: (without chai as promised)
```
var data;
var capture = callSomeFunc().then(function (item) {
   data = item;
});

/* Expect inside .then(). Will propogate to a catch closure */
capture = capture.then(function () {
  expect(data).to.equal(5);
});

/* Instead of .notify  */
capture.then(function () {
  done();
}, function (e) {
  done(e);
});
```

It works, but I was hoping chai-as-promised would do most of the code in this example.

note: the same can done when expecting failure. Just call done() on the catch closure, and done("Shouldn't be here) on the .then() closure.

**Comment by keithamus** [comment]
Mocha has built in support for returning Promises, which you should probably use. Simply return the Promise, and omit all `done`s - like so:

```js
it('should deep equal data', function () {
  var data1;
  return expect(...then(function(data2, data3) {
    expect(data1).to.equal(0);
    expect(data3).to.equal(5);
    expect(data3).to.equal(5);
  }))
});
```

Also you can use all of the same Chai functions with Chai-As-Promised, including deep.property/deep.equal:

````js
it('should deep equal data', function () {
  return expect(promise).to.eventually.deep.equal([0, 5, 5]);
});
```

**Comment by domenic** [comment]
Right, it's still a bit hard to tell what's going on due to the invalid notation in the OP, but @keithamus's answer should point you in the right direction. If I were to rewrite your valid code from https://github.com/domenic/chai-as-promised/issues/112#issuecomment-113865748, I would indeed do

```js
it('should deep equal data', function () {
  return expect(callSomeFunc()).to.eventually.equal(5);
});
```

Closing since this isn't a bug in Chai as Promised, but feel free to continue discussion.

**Comment by matanshukry** [comment]
I'm not sure you understand me, or vice versa?

Anyway, here is a _working_ code, yet it's using the workaround I showed.

```
    it('Should call cli.runMain()', function(done) {
      var cliRunMainProc = stubAsPromised(cli, 'runMain');
      var processExitProc = stubAsPromised(process, 'exit');
      var processArgs = Promise.resolve(process.argv).disposer(function (oldArgsIn) {
        process.argv = oldArgsIn;
      });

      Promise.using(cliRunMainProc, processExitProc, processArgs,
                    function (cliRunMainStub, processExitStub) {
        process.argv = ['node main.js'];
        
        require(MAIN_PATH);
        
        expect(processExitStub.callCount).to.be.equal(0);

        /*jshint expr: true */
        expect(cliRunMainStub.calledOnce).to.be.true;
      }).then(function () {
        done();
      }).catch(function (e) {
        done(e);
      });
    });
```

The only other way I thought on doing it, was this:

```
    it('Should call cli.runMain()', function(done) {
      var cliRunMainProc = stubAsPromised(cli, 'runMain');
      var processExitProc = stubAsPromised(process, 'exit');
      var processArgs = Promise.resolve(process.argv).disposer(function (oldArgsIn) {
        process.argv = oldArgsIn;
      });

      var tmpCliRunMainStub;
      var tmpProcessExitStub;
      return Promise.using(cliRunMainProc, processExitProc, processArgs,
                    function (cliRunMainStub, processExitStub) {
        process.argv = ['node main.js'];
        
        tmpCliRunMainStub = cliRunMainStub;
        tmpProcessExitStub = processExitStub;
        
        require(MAIN_PATH);
      }).then(function () {
        expect(processExitStub.callCount).to.be.equal(0);
        expect(cliRunMainStub.calledOnce).to.be.true;

        done();
      });
    });
```

The problem with it, as I already wrote, is an exception is thrown rather than being a result of a test;
```
Unhandled rejection AssertionError: expected false to be true
```

How would you re-write the first code block then?

p.s.
If you're wondering what I'm doing in the code, I'm testing a CLI tool, specifically the main file of it.
What it _should_ do is call cli.runMain(), once. On any error, it will print and call process.exit(), hence the stubbing of it too. Be that as it may, the actual code isn't really relevant here.

**Comment by domenic** [comment]
You should never use the done() parameter; always use the promise-returning Mocha functionality instead. (NOT in addition to.)

**Comment by domenic** [comment]
> Unhandled rejection 

This does not mean an error is being thrown; it means Bluebird is giving you spurious errors due to its over-eager unhandled rejection reporting. Might be worth opening an issue on the Bluebird tracker?

**Comment by matanshukry** [comment]
1. Not using the 'done' parameter doesn't make any sense. When not using it, the test case will be synchronous. The done parameter allows you to control when the test is done, rather than expecting the test to be done after all calls are made (the first is needed when dealing with asynchronous code)

Correct me if I'm wrong?

2. I might be wrong here, but as far as I can tell, chai is throwing an exception on the except() call (when needed), and the test (mocha?) catch that exception (I'm guessing a specific case of exception), in which case it recognize it as a test failure.

Bluebird, wraps up any exception with their own type, allowing you to catch them with .catch().

Now, since there is no .catch(), the exception is bubbling outside/up. Mocha is seeing it, but that is not the usual exception, hence throws it.

---
In my opinion, the correct result should be somewhere with .catch() and .done().
Since it is using both chai and bluebird, I think it should be in chai-as-promised responsibility.

**Comment by keithamus** [comment]
@matanshukry 

1. Mocha can handle Promises, the capability is baked in. Not using `done`, but returning a `Promise` makes perfect sense - mocha knows you've returned a Promise and will act accordingly, therefore you do not need a done. Try it and you'll see :wink: 

2. Mocha will also (given a returned promise) use catch() and will indeed catch any errors. You shouldn't need any `catch()` in your code (unless you specifically want to catch an error and not fail the test with it).

**Comment by keithamus** [comment]
@matanshukry here is an example of real running test code, that actually passes against my codebase. It uses chai-as-promised and mocha, it returns a Promise - and also has a `.then()`. 

```js
it('successfully deletes a user', function () {
            return app.del('/user/' + id)
                .should.eventually.have.status(200)
                .and.be.json
                .then(function () {
                    return app.get('/user/' + id);
                })
                .should.eventually.have.status(404)
                .and.be.json;
        });
```

Any errors caught in the Promise chain will be handled by mocha, because I've returned the Promise, and Mocha knows about Promises. Just to further prove I'm not making this up, [here is the source code for mocha, where it detects if the return value is a "thennable" (Promise)](https://github.com/mochajs/mocha/blob/d71a5c6e0f17ab5b530388edf5b8cfb71ed75d33/lib/runnable.js#L262-L276) and here are [Mocha's own unit tests that ensure that Promises are dealt with](https://github.com/mochajs/mocha/blob/7493bca76662318183e55294e906a4107433e20e/test/runnable.js#L302-L410).

**Comment by matanshukry** [comment]
You are correct.
I had no idea about this feature with mocha, and simply didn't even think on returning the Promise.
I apologize for that.
