### ISSUE TITLE
Promise rejection are detected fulfilled using babel await/async + should

### ISSUE THREAD

**Issue by n1k0** [domenic/chai-as-promised#114]
Environment:

- nodejs v0.12
- babel v5.6.14
- mocha v2.2.5
- chai v3.0.0
- chai-as-promised v5.1.0

Test cases:

```js
describe.only("async/await tests", function() {
  async function test() {
    return Promise.reject("plop");
  }

  it("should work using should", function() {
    return test().should.be.eventually.rejectedWith("plop");
  });

  it("should work using expect", function() {
    expect(test()).to.be.eventually.rejectedWith("plop");
  });
});
```

Results:

```
  tests
    1) should work using should
    ✓ should work using expect


  1 passing (4ms)
  1 failing

  1) tests should work using should:
     AssertionError: expected promise to be rejected with an error including 'plop' but it was fulfilled with undefined
```

If I change the test() function so it throws instead of returning a rejecting promise, it works.
It also works if I remove the `async` keyword, obviously.

Maybe that's just me misunderstanding the spec (I'm rather new to async/await), though I found the different behaviors between *should* and *expect* quite confusing :)

**Comment by domenic** [comment]
You forgot to return in the second one, that's why there's a difference.

Anyway, the first fails because rejectedWith (like Chai's throw) is meant to be used with Error objects, not strings. You should never reject promises with strings, just like you should never throw strings. http://www.devthought.com/2011/12/22/a-string-is-not-an-error/

**Comment by n1k0** [comment]
I've updated the test code and it's still failing:

```js
describe.only("tests", function() {
  async function test() {
    return Promise.reject(new Error("plop"));
  }

  it("should work using should", function() {
    return test().should.be.eventually.rejectedWith(Error, "plop");
  });

  it("should work using expect", function() {
    expect(test()).to.be.eventually.rejectedWith("plop");
  });
});
```

Results:

```
  tests
    1) should work using should
    ✓ should work using expect


  1 passing (8ms)
  1 failing
```

I don't think returning is required using `expect`. Even if I do so, both tests fail. I feel like I'm missing something, but to me this is still an issue. Your call on reopening.

**Comment by domenic** [comment]
Returning is required. Also, don't use eventually with rejectedWith. eventually is for traditional Chat assertions that need to become async.

**Comment by n1k0** [comment]
> Returning is required. Also, don't use eventually with rejectedWith

Oh, thanks for the tips :)

So I've updated test code and it's now failing in both cases:

```js
describe.only("tests", function() {
  async function test() {
    return Promise.reject(new Error("plop"));
  }

  it("should work using should", function() {
    return test().should.be.rejectedWith(Error, "plop");
  });

  it("should work using expect", function() {
    return expect(test()).to.be.rejectedWith(Error, "plop");
  });
});
```

Results:

```
  tests
    1) should work using should
    2) should work using expect


  0 passing (6ms)
  2 failing

  1) tests should work using should:
     AssertionError: expected promise to be rejected with 'Error' but it was fulfilled with undefined


  2) tests should work using expect:
     AssertionError: expected promise to be rejected with 'Error' but it was fulfilled with undefined
```

Which makes me wondering if that's expected behavior. Sorry to bother you with all this, and thanks for taking the time to help.

**Comment by n1k0** [comment]
Updated test code to add tests cases for fulfillment:

```js
describe.only("tests", function() {
  describe("fulfillment", function() {
    async function test() {
      return Promise.resolve(42);
    }

    it("should work using should", function() {
      return test().should.become(42);
    });

    it("should work using expect", function() {
      return expect(test()).to.become(42);
    });
  });

  describe("rejection", function() {
    async function test() {
      return Promise.reject(new Error("plop"));
    }

    it("should work using should", function() {
      return test().should.be.rejectedWith(Error, "plop");
    });

    it("should work using expect", function() {
      return expect(test()).to.be.rejectedWith(Error, "plop");
    });
  });
});
```

Results:

```
  tests
    fulfillment
      ✓ should work using should
      ✓ should work using expect
    rejection
      1) should work using should
      2) should work using expect


  2 passing (5ms)
  2 failing

  1) tests rejection should work using should:
     AssertionError: expected promise to be rejected with 'Error' but it was fulfilled with undefined


  2) tests rejection should work using expect:
     AssertionError: expected promise to be rejected with 'Error' but it was fulfilled with undefined
```

**Comment by n1k0** [comment]
Hmm, using Babel's playground I realize the possible issue is on their side: http://tinyurl.com/pagzzaw

So this is not related to chai-as-promised, it's even possible that's me doing things wrong. Sorry for the noise.

**Comment by keithamus** [comment]
I have a feeling you might be using async functions wrong. Returning a Promise doesn't really make much sense as async functions are meant to be an abstraction over promises. Either drop the async, or use async abstraction as intended:

```js
// Drop async
function test() {
    return Promise.reject(new Error("plop"));
}

// Use async as intended
async function test() {
    throw new Error("plop");
}
```

**Comment by n1k0** [comment]
You are obviously right. TBH I was trying to simplify an issue I'm encountering with some indexedDB code, where:

```js
async get(id, options={includeDeleted: false}) {
    try {
      await this.open();
      return new Promise((resolve, reject) => {
        const {transaction, store} = this.prepare();
        const request = store.get(id);
        transaction.onerror = event => reject(new Error(event.target.error));
        transaction.oncomplete = event => {
          if (!request.result ||
             (!options.includeDeleted && request.result._status === "deleted")) {
            // WTF, this doesn't actually reject, the promise is fulfilled
            reject(new Error(`Record with id=${id} not found.`));
          } else {
            resolve({
              data: request.result,
              permissions: {}
            });
          }
        };
      })
    } catch(err) {
      this._handleError("get")(err);
    }
  }
```

Would you by chance have any idea ho to throw from within a nested promise that way, so the parent one is actually rejected?

Note: so sorry to bother you with this here, feel free to redirect me elsewhere or simply ignore it.

**Comment by keithamus** [comment]
Try turning your `return new Promise` into `await new Promise` and see what happens. Being in a try/catch though - any rejections from the Promise will fall into your `catch(err)` which if you dont want, you'll have to move the `await new Promise` bit into a `finally`.

**Comment by n1k0** [comment]
Thanks for the hint, `return await ne Promise(…)` actually solves my issue:

```js
async get(id, options={includeDeleted: false}) {
    try {
      await this.open();
      return await new Promise((resolve, reject) => {
…
            reject(new Error(`Record with id=${id} not found.`));
…
      });
    } catch(err) {
      this._handleError("get")(err);
    }
  }
```

Sorry again for the pollution, and thanks again for the help provided.

**Comment by n1k0** [comment]
Ah, just learned that there were an actual issue regarding this with Babel: https://github.com/babel/babel/issues/1853; I'll probably hold on using all this until it's a little more stabilized :)
