### ISSUE TITLE
`return` is required for promise assertions

### ISSUE THREAD

**Issue by btbonval** [domenic/chai-as-promised#116]
I just found out all of my promise-based assertions were incorrect because I was not returning them. Without returning them, no assertions are raised. For example, this code will always pass no matter what is returned into `promise` (even a `reject()`) so long as it is thenable:

``` javascript
  it('returns data via promise without modification', function() {
    var promise = cdbfuncs.fetchDocs(mock_http, urlFixture);
    expect(promise).to.eventually.deep.equal(dl_data);
  });
```

It took me a close reading of the README to realize the `return` used in nearly every example was there (there are some without it). Since the examples were without context, it wasn't clear the `return` was necessary or an artifact of the example's context.

``` javascript
it('returns data via promise without modification', function() {
    var promise = cdbfuncs.fetchDocs(mock_http, urlFixture);
    return expect(promise).to.eventually.deep.equal(dl_data);
  });
```

My team has been building multiple assertions inside a single `it()`. I had decided to restructure my code for one assertions per `it()` by sheer coincidence. While Chai assertions can be bundled together line-by-line in a single `it()`, Chai-as-Promised can only support a single assertion per `it()`.

I'm fine with this workflow. However, it might be beneficial to explain this explicitly in fairly big lettering in the README. Something along the lines of "Each assertion of Chai-as-Promised must be returned or it will give erroneous results. The recommended workflow is a single assertion per `it()`.".

**Comment by keithamus** [comment]
Hey @btbonval thanks for the issue.

This kind of gap in documentation is best written by the person that found it - which is a roundabout way of saying, if you'd like to alter the documentation to how _you think_ it should read, and send a PR, and we'll take a look :smile:

**Comment by domenic** [comment]
Yeah, I feel like we make this pretty clear, so I'm curious how you think it should be changed.

Remember that only some test runners support `return`, and others need the `.notify(done)`, so any PR you'd need to be sure to emphasize both possibilities.

**Comment by btbonval** [comment]
Interesting. I didn't realize the scope/variety of test runners.

My particular use case is Mocha, so maybe I'll write a specific section about the specific combination Mocha + Chai + Chai-As-Promised which highlights that return must be used for promise assertions, or else they will always appear okay whether or not they are.

Mocha + Chai doesn't require the returns, nor does Chai make much use of return in its documentation, which is primarily where I ran into problems. I figured Chai-As-Promised was following Chai syntax and convention, which is how I so easily ignored return in every example ;)

**Comment by keithamus** [comment]
Just to be clear, Chai-As-Promised doesn't require returns either. It's just a convenient shortcut, considering Mocha supports returning a Promise to run an async test. Mocha still can use `.notify(done)` without `return`. You could also always `return`, even with normal chai assertions, with no problems within Mocha.

**Comment by btbonval** [comment]
I did not realize `.notify(done)` applied in my use case.

Maybe my confusion is the case in which `.notify(done)` should be used. I'll reread that part of the documentation and see why it did not click with me that `.notify(done)` should be applied to Mocha.

**Comment by TimeForAChange** [comment]
This caught me too - twice, actually (seems like it didn't sink in the first time). I re-read the documentation webpage and it only mentions to use `.notifiy

**Comment by keithamus** [comment]
@TimeForAChange if you'd like to write some documentation to clarify this, and put it in a PR, it'd be very welcome :smile:

**Comment by TimeForAChange** [comment]
I know, but I won't. Not my package.

**Comment by btbonval** [comment]
@TimeForAChange if nothing else it was a reminder that I was asked to write a documentation update on this issue. A little peer pressure can be a helpful reminder.

I know a lot of projects are down on people adding +1 comments on issues, I didn't see anyone mention that here. Either someone edited their comments, or you might be jumping to react to a situation which has not occurred.

When I use GitHub for professional work (as I am doing now), I tend not to do any sort of programming work on the side, and I also forget look at anything on GitHub besides my paid work. For my own part, a PR might be a long time in coming unless I do it right now, but actually, I just sat down to do other work when I saw this (of course).

**Comment by keithamus** [comment]
PRs are not obligatory and neither of you should feel guilty or otherwise pressured into making them. If you do, fantastic - many thanks from the maintainers and future users of the software! If you don't, not big deal :smile:

**Comment by btbonval** [comment]
@keithamus Although `return` is not necessary, and `notify(done)` could be used, I think the real issue I have here is when there are multiple assertions in a single `it`.

`return` cannot be used for multiple promise assertions inside a single `it`. `notify(done)` is the only solution to having multiple promise assertions, but you must aggregate the promises using something like `RSVP.all(...).then(done)`. I don't know if `all()` is part of any of the promise standards or just a good idea implemented in `RSVP`.

**Comment by btbonval** [comment]
There, I think I managed to really highlight what I was missing initially with the notice, while also drawing more attention to `return` (marking it as code in the English text where it is mentioned). 

I also added a section for managing multiple assertions in a single section, which gets a bit more into the `return` vs `done` difference.
