### ISSUE TITLE
Should.be.rejected.with(Error) compares for same error object, not equal

### ISSUE THREAD

**Issue by philosoralphter** [domenic/chai-as-promised#120]
This shouldn't happen:

`Unhandled rejection AssertionError: expected promise to be rejected with [Error: Could not find route to handle path: /test/wrong/path] but it was rejected with [Error: Could not find route to handle path: /test/wrong/path]`

If this assertion is checking that the error object created in the code is the exact same object as the one I create in the test, then it will never be of use.  They are different objects that need to be compared for properties, etc., not identity.

I'm sure this works with string rejection reasons, but It should also work with error objects because those are more useful.

**Comment by domenic** [comment]
It is intended to work the same as Chai's assert.throws. It mismatches in some edge cases; see #47. But I believe this is the same behavior as Chai, and so we're not going to change it in the way you describe.

**Comment by philosoralphter** [comment]
Thanks @domenic .  I should have looked into it further.
