### ISSUE TITLE
Don't reject jQuery >= 3.0.0

### ISSUE THREAD

**Issue by mgol** [domenic/chai-as-promised#121]
jQuery 3.0 & jQuery Compat 3.0 promises will be Promises/A+-compliant (current `master` & `3.0.0-alpha1` pass the whole `promises-aplus-tests@2.1.0` suite, we have it enforced in CI) so it'd be good if Chai as Promised didn't reject them.

jQuery 3.0 adds `catch` (defined as `fn => promise.then(null, fn)`) to its promises so it should be enough to modify [this check](https://github.com/domenic/chai-as-promised/blob/5dcfee7fa3f3532964680dff2c13547677c0157e/lib/chai-as-promised.js#L37-L44); if `thenable.catch` exists, the promise should be fine.

Please let us know if there are still some problems that would prevent you to consume jQuery Promises. You can test on `jquery@beta`.

**Comment by keithamus** [comment]
@mzgol would it be too cheeky to request a PR fixing this? I understand if your plate is full but it seems like it'd be a good idea as you have the best grasp of the issue.

**Comment by mzgol** [comment]
Sure, I can submit a PR. I just wanted to get some feedback first. :)

**Comment by domenic** [comment]
Yeah, seems good. Probably also want to modify the error message a bit later.

**Comment by mzgol** [comment]
WIP PR: #122. I need some help with it (3 tests are failing).

**Comment by domenic** [comment]
Fixed in v5.3.0.
