### ISSUE TITLE
Testing multiple promises sequentially

### ISSUE THREAD

**Issue by arisAlexis** [domenic/chai-as-promised#124]
I would like to use this suite for integration style tests meaning I want to retrieve a user, test his email is correct then change it then test his email changed.
I cannot find how to do that.

This code fails the first test of course because when it is resolved the email is already changed.

    it.only('find a user and update him',()=>{
        let user=userStore.find('testUser1').then((u)=> {
            u.email='random@email';
            u.location = 'austin,texas,usa';
            return userStore.save(u);
        });

        return Promise.all([
            user.should.eventually.have.property('email','testUser1@email.com'),
            user.should.eventually.have.property('email','random@email'),
            user.should.eventually.have.property('location','austin,texas,usa'),
            ]);
    });

**Comment by blah238** [comment]
If you're using [Bluebird](https://github.com/petkaantonov/bluebird), try [`Promise.reduce`](https://github.com/petkaantonov/bluebird/blob/master/API.md#reducefunction-reducer--dynamic-initialvalue---promise) or [`Promise.map`](https://github.com/petkaantonov/bluebird/blob/master/API.md#mapfunction-mapper--object-options---promise) with `1` for the [`concurrency`](https://github.com/petkaantonov/bluebird/blob/master/API.md#option-concurrency) option.

**Comment by arisAlexis** [comment]
I used this approach with intermediate promise "snapshots" suggested in an SO post:

it('follow and unfollow',()=>{

        const follow=userService.follow('testUser1','testUser2');
        const followSecond=follow.then(userService.follow('testUser3','testUser2'));
        const getFollowers=followSecond.then(()=>userService.getFollowers('testUser2'));
        const unfollow=getFollowers.then(()=>userService.unfollow('testUser1','testUser2')).then(()=>userService.getFollowers('testUser2'));
        const getFollowees=unfollow.then(()=>userService.getFollowees('testUser3'));

        return Promise.all([
            getFollowers.should.eventually.have.deep.property('[1].username'),//todo testing sorted by since field is not working
            getFollowers.should.eventually.have.length(2),
            unfollow.should.eventually.have.length(1),
            getFollowees.should.eventually.have.deep.property('[0].username','testUser2'),
            ]);
    });

**Comment by arisAlexis** [comment]
I love the way this flows and thought I could share it here. 

    it.only('find async a user and update him',()=>{
        return async function () {
            let user=await userService.find('testUser1');
            expect(user).to.have.property('email','testUser1@email.com');
            user.location = 'austin,texas,usa';
            let savedUser=await userService.update(user);
            expect(savedUser).to.have.property('location','austin,texas,usa');
        }();
    });

**Comment by keithamus** [comment]
@arisAlexis you should be able to shorten that and pass the async function to it: 

```js
it.only('find async a user and update him', async function () {
    let user = await userService.find('testUser1');
    expect(user).to.have.property('email','testUser1@email.com');
    user.location = 'austin,texas,usa';
    let savedUser = await userService.update(user);
    expect(savedUser).to.have.property('location','austin,texas,usa');
});
```

**Comment by arisAlexis** [comment]
that is even better @keithamus ! now it looks like a real integration test :)

**Comment by keithamus** [comment]
Also - if you wanted to, you could forgo having vars like `savedUser`. Although I do think they make it more readable, but just to illustrate a point:

```js
it.only('find async a user and update him', async function () {
    let user = await userService.find('testUser1');
    expect(user).to.have.property('email','testUser1@email.com');
    user.location = 'austin,texas,usa';
    expect(await userService.update(user)).to.have.property('location','austin,texas,usa');
});
```

Anyway - I'm going to mark this one as closed, there's many ways to skin it, async/await is obviously the nicest, but otherwise simply returning a Promise or perhaps using prfun/bluebird to do a Promise.series would work fine here. Thanks for coming back and posting your final code here @arisAlexis :smile:

**Comment by domenic** [comment]
Yeah, if you have an async function, you don't need chai as promised at all, you can just use regular chai.
