### ISSUE TITLE
add website to Github repo

### ISSUE THREAD

**Issue by gr2m** [domenic/chai-as-promised#134]
would be nice to get the website next to he repo description like you see it with many other projects

**Comment by domenic** [comment]
This project does not have a website besides GitHub.

**Comment by gr2m** [comment]
sorry I thought this would be the one:
http://chaijs.com/plugins/chai-as-promised

**Comment by domenic** [comment]
I don't maintain that website. I think it scrapes my readme?

**Comment by gr2m** [comment]
nevermind then :) thanks for the quick response Domenic
