### ISSUE TITLE
Assert interface can't handle promise returned by webdriver

### ISSUE THREAD

**Issue by arturgorski** [domenic/chai-as-promised#137]
Promises generated by webdriver are sealed and it's impossible to add notify method to this promise. It causes an error:
```
 TypeError: Can't add property notify, object is not extensible
 at Object.assert.eventually.(anonymous function) [as equal] (chai-as-promised\lib\chai-as-promised.js:363:40)
```

I've created [example project to reproduce this error](https://github.com/arturgorski/project-to-reproduce-error-in-chai-as-promissed)

**Comment by domenic** [comment]
Fixed per https://github.com/domenic/chai-as-promised/pull/138#issuecomment-183514217 on the Selenium side, thankfully.
