### ISSUE TITLE
Chai-as-promised does not support es6 native promises

### ISSUE THREAD

**Issue by lobobabysaurus** [domenic/chai-as-promised#139]
When running a chai-as-promised assertion on an es6 native promise it returns an error stating `TypeError: Cannot set property then of [object Object] which has only a getter` 

can run `Promise.resolve(2+2).should.eventually.equal(4);` with ES6 to reproduce the issue

**Comment by domenic** [comment]
Can you create a small working example I can run in Node.js?

**Comment by lobobabysaurus** [comment]
Isolating the issue and running it let chai-as-promised work fine, so it has to be something weird with my own setup in a separate project.  closing it
