### ISSUE TITLE
Support Use Alongside sinon-chai-in-order

### ISSUE THREAD

**Issue by lobobabysaurus** [domenic/chai-as-promised#140]
When [sinon-chai-in-order](https://www.npmjs.com/package/sinon-chai-in-order) is also used as a chai plugin, chai-as-promised begins to show a host of problems.  Particularly I have seen consistent `TypeError: Cannot set property then of [object Object] which has only a getter` and `RangeError: Maximum call stack size exceeded` errors.

I'm not sure how much can be done or how much coordination would need to happen between the two plugin projects, but it is a real pain to have to pick between which super useful plugin to use.

Here is some example code in ES6 which allows reproduction of the issue and requires chai, chai-as-promised and sinon-chai-in-order to be installed

    import chai from 'chai';
    import sinonChaiInOrder from 'sinon-chai-in-order';
    import chaiAsPromised from 'chai-as-promised';

    chai.should();
    chai.use(chaiAsPromised);
    chai.use(sinonChaiInOrder);

    describe('chai as promised', () => {
      it('should properly handle es6 promises', () => {
        Promise.resolve(2+2).should.eventually.equal(4);
      })
    });

If they cant be used simultaneously I think the minimum that should happen should be a note in the README which warns people about the compatibility issue to hopefully save some time and frustration.

Same issue has been raised on sinon-chai-in-order [here](https://github.com/electricmonk/sinon-chai-in-order/issues/2)

**Comment by keithamus** [comment]
Thanks for the issue @lobobabysaurus.

As @electricmonk points out in [this comment on the sinon-chai-in-order issue](https://github.com/electricmonk/sinon-chai-in-order/issues/2#issuecomment-192843180) - this is an issue with that plugin. Thanks for your time in filing this. I'll close this, as it is not our bug, but if you have any more issues feel free to raise them :smile:.

**Comment by electricmonk** [comment]
We'll, as a matter of fact I said (at least I meant to say) that the fault is with Chai As Promised, which attempts to set a `then` method on the assertion even though one already exists.

—
http://www.shaiyallin.com

**Comment by keithamus** [comment]
Okay, I'll reopen this for now.

**Comment by lobobabysaurus** [comment]
Sinon-chai-in-order has been modified to no longer try to use 'then' so this conflict should no longer occur
