### ISSUE TITLE
A modified Promise is incorrectly labeled as a jQuery Promise

### ISSUE THREAD

**Issue by not-an-aardvark** [domenic/chai-as-promised#142]
This is enough of an edge-case that it might not be worth fixing, but I thought I'd bring it up nonetheless.

My [promise-chains](/not-an-aardvark/promise-chains) tool uses ES2015 Proxies to chain properties off of Promises. For example, given some `wrappedPromise`, `wrappedPromise.someProperty` is equivalent to `wrappedPromise.then(result => result.someProperty)`. Internally, the proxied Promises are stored as functions, because this allows them to use the ['apply' handler](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/apply).

As a result, `typeof wrappedPromise.someProperty === 'function'` is always true. So [this function](/domenic/chai-as-promised/blob/c0d887605a6df879d7ff1700600ad450e6e09a84/lib/chai-as-promised.js#L37), which is supposed to detect jQuery Promises, ends up giving a false positive. The effect of this is that chai-as-promised throws an error and refuses to touch the modified Promise, even though it's a perfectly valid thenable.

**Comment by domenic** [comment]
Maybe we could also test for the property "notAJQueryPromise". Since your library would pass that, this would solve it. Pull request welcome.

**Comment by domenic** [comment]
This is fixed in master, I guess, since we now flag anything with a `catch` method as not a legacy jQuery promise.
