### ISSUE TITLE
Documented expect-interfaces missing

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [domenic/chai-as-promised#143]
At least the following expect-interfaces do not work even though they are documented in the README: `be.fulfiled, be.rejected`

### Example

**Code**:
```js
var chai = require('chai'),
expect = chai.expect;

chai.use(require('chai-as-promised'));

expect(new Promise(function(){})).to.be.fulfilled();
```
**Throws**: `TypeError: expect(...).to.be.fulfilled is not a function`

**Comment by domenic** [comment]
They're not functions, they're properties. As already documented in the readme.
