### ISSUE TITLE
Testing a rejected promise with to.have.property(...) returns true

### ISSUE THREAD

**Issue by rvnath** [domenic/chai-as-promised#144]
I am running a simple test to check the return value of a promise, as below:
```javascript
var chai = require('chai');
var chaiHttp = require('chai-http');
var expect = chai.expect;
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);

describe('simple test', function() {
  it('Test should fail for a rejected promise', function() {
    return expect(Promise.reject(false)).to.eventually.have.property('hello');
  });
});
describe('simple test', function() {
  it('Test should fail for a rejected promise', function(done) {
    return expect(Promise.reject(false)).to.eventually.have.property('hello').and.notify(done);
  });
});
```
When I run the above suite, 1st test case passes, while the 2nd one fails.  Ideally, both test cases should be failing.  It seems that the framework should be able to call done callback with err value, which probably isn't doing it?    This is the output:

>   simple test
>     1) Test should fail for a rejected promise
>   simple test
>     ✓ Test should fail for a rejected promise
>   1 passing (15ms)
>   1 failing
> 
>   1) simple test Test should fail for a rejected promise:
>      Error: Promise rejected with no or falsy reason
> 

Is my hypothesis correct?  How do I get this working, if not?

**Comment by domenic** [comment]
The second one doesn't make sense, as it's both returning and using done().

Your output shows the first failing (as it should), and the second passing (which I am not sure about, but since the test makes no sense don't know what to expect).
