### ISSUE TITLE
Plugins added after chai-as-promised is required

### ISSUE THREAD

**Issue by dareid** [domenic/chai-as-promised#145]
I believe currently chai-as-promised finds all registered assertions and promisifies them. If custom plugins are added later, these new assertions are not promisified. 

Is there anyway the method which promisifies assertions could be exposed. This would allow new plugins to be promisified if required. My motivation behind this is for the Chakram library which heavily uses chai-as-promised and struggles with users adding new plugins.

**Comment by adelespinasse** [comment]
I just discovered this issue the hard way. I was loading `chai-as-promised` and then `chai-match-pattern`, but when I did something like `expect(x).to.eventually.matchPattern(pattern)` it didn't work. I was lucky enough to guess that I needed to load the plugins in the opposite order.

I'd like to suggest that, if this can't be fixed easily, at least the README.md should recommend loading `chai-as-promised` last, with an explanation of why.
