### ISSUE TITLE
Self is undefined in module system setup

### ISSUE THREAD

**Issue by Astridax** [domenic/chai-as-promised#148]
Hey, I've been trying to get chai-as-promised to work well with Karma and Nativescript, using Nativescript's . Nativescript uses Karma and the help of a test helper app to run tests against the test helper app and report the results back to Karma running on the host machine. 

This snippet of code is causing problems: 
```
if (typeof require === "function" && typeof exports === "object" && typeof module === "object") {
        // NodeJS
        module.exports = chaiAsPromised;
    } else if (typeof define === "function" && define.amd) {
        // AMD
        define(function () {
            return chaiAsPromised;
        });
    } else {
        /*global self: false */
        // Other environment (usually <script> tag): plug in to global chai instance directly.
        chai.use(chaiAsPromised);

        // Expose as a property of the global object so that consumers can configure the transferPromiseness property.
        self.chaiAsPromised = chaiAsPromised;
    }
```

The self object doesn't exist in this case. Obviously commenting out the self.chaiAsPromised fixes the situation, but I don't want to make a pull request of something like if(self) self.chaiAsPromised = chaiAsPromised because it would break functionality silently for anyone else in my position. 

I've checked sinon-chai which has very similar module loading code and it simply omits the reference to self. 

The code was originally committed here:
https://github.com/domenic/chai-as-promised/commit/cb59ba97b527cd5848d88fc3f1aea045d856a4bd

I'm not entirely sure why self doesn't exist and I'm not sure what other global variables I could attach the function to.

A second pair of eyes would be appreciated, but for the moment I'll continue with my hacky fix because I didn't need the added functionality anyway.

**Comment by domenic** [comment]
It sounds like Nativescript doesn't have a `self` global. So, it isn't a supported environment, and you'll need to use hacks (such as creating a global `self` property before loading Chai as Promised).

**Comment by Astridax** [comment]
See I'm not entirely sure how to go about creating a global self property in this case, or making it available to pre-existing modules like Chai as Promised. I'm also not entirely sure how node modules run within nativescript since at least from the context of Chai as Promised the 'module' variable as in module.exports etc doesn't exist at all, well at least not when running in a test. Yet if that were the case for all code most of the node modules I'm using wouldn't work at all.

Got any ideas?

**Comment by domenic** [comment]
I have no familiarity with Nativescript, so I don't really have any ideas, sorry.

**Comment by Astridax** [comment]
It's fine thanks, I'll ask around there and point them to this thread. See if they have any ideas.

**Comment by Astridax** [comment]
Okay I think I have found a solution in this case that keeps all existing functionality. I'll fork the repo and submit a pull request.

**Comment by domenic** [comment]
Please do not do that. Native script is not supported.
