### ISSUE TITLE
promised functions always  passes regardless of output values

### ISSUE THREAD

**Issue by HKskn** [domenic/chai-as-promised#151]
Hi,
I wrote a method which returns promise then when i tested the method with unexpected values, it always end up with same pass message. Then i tested basic example from your readme file.

  expect(Promise.resolve(2 + 2)).to.eventually.equal('3');

it passes too, could you help me about on this issue.

**Comment by domenic** [comment]
You seem to have forgotten a return statement.

**Comment by HKskn** [comment]
i tried with this statement,
           expect((function(){return Q.resolve(2 + 2)})()).to.eventually.equal('3');
and still passes.

**Comment by HKskn** [comment]
i understand now :), thank you.
i have use return like ,

return expect(Q.resolve(2+2)).to.eventually.equal('3');
