### ISSUE TITLE
Did the syntax change?

### ISSUE THREAD

**Issue by peterjuras** [domenic/chai-as-promised#154]
Hi.

Did the expect syntax change from expect(promise).to.be.**fulfilled**; to expect(promise).to.be.**fullfilled()**?
I had issues while getting my unit tests to work, with my unit test being:

```js
import chaiAsPromised from 'chai-as-promised';
import dirtyChai from 'dirty-chai';
import chai, { expect } from 'chai';

chai.use(dirtyChai);
chai.use(chaiAsPromised);

// ...
it('should reject if file transfer was not successful', async () => {
  fileTransferShouldResolve(false); // Promise will reject
  // uploadFile returns Promise
  return expect(uploadFile(fileUrl, serverUrl)).to.be.fulfilled;
});
```
The above unit test passed, leaving the rejected error only on the console. The correct behavior would have been if the test would fail. Changing the syntax to the following line resolved the issue and made my test fail with the correct reason:
```js
// ...
return expect(uploadFile(fileUrl, serverUrl)).to.be.fulfilled();
```

**Comment by keithamus** [comment]
Hey @peterjuras thanks for the issue.

You're using `dirty-chai` which turns all property assertions (like `fulfilled`) into methods (so `fulfilled()`). Nothing has changed in chai-as-promised though. If you want to keep the original behaviour, just dont import dirty-chai

I'll close this, as hopefully that answers your question, let us know if you have any other issues!

**Comment by peterjuras** [comment]
Thanks for the quick response!
