### ISSUE TITLE
Add a promise chaining method

### ISSUE THREAD

**Issue by maxnordlund** [domenic/chai-as-promised#156]
Hi, thanks for this awesome library. When I was writing some tests today I realized I needed to do a separate assertion after some promise hade resolved, so I just used `.then`. But it didn't read very well, and I though there should be a better way.

After some tinkering I got this:
```javascript
const chai = require("chai")

chai.use((_chai, utils) => {
  chai.Assertion.addMethod("andThen", function andThen(newExpected) {
    // By setting the `eventually` flag, chai as promised plays along nicely
    this._obj = Promise.resolve(newExpected)
    utils.flag(this, "eventually", true)
  })
})

// Has to call this last to make it pick up everything else
chai.use(require("chai-as-promised"))
```

Which is used kinda like so:
```javascript
let foo = {
  bar() { return Promise.resolve().then(() => this.baz()),
  baz() {}
}

describe("foo", () => {
  it("has side effects", () => {
    sinon.spy(foo, "baz") // Using sinon+sinon-chai
    return expect(foo.bar()).to.be.fufilled.andThen(foo.baz).to.have.been.called
  })
})
```

Does this make sense to you? Should it be included with chai-as-promised or is it out of scope? Any other feedback very much appreciated.

**Comment by domenic** [comment]
I think I would prefer people use JavaScript's built-in chaining mechanism for promises, i.e. `.then` and `async`/`await`. If you're interested in making a separate Chai plugin with your helper, I'm happy to link to it from the readme, though.

**Comment by maxnordlund** [comment]
I hadn't thought about `async`/`await`, it would read the best, so something like:

```javascript
describe("something async", () => {
  it("uses async/await", async function testCase() {
    await expect(foo.bar()).to.be.fufilled
    await expect(foo.baz).to.have.been.called
    // ^ can use return instead but it doesn't read as nice
  })
})
```

Yeah, I'll make this a separate plugin then. Thanks for the feedback.

**Comment by keithamus** [comment]
@maxnordlund just a tip: you won't need to use chai-as-promised assertions if you use async/await, and you should only await on the promise-rerturning parts, so something like:

```js
describe("something async", () => {
  it("uses async/await", async function testCase() {
    await foo.bar()
    expect(foo.baz).to.have.been.called
  })
})
```

**Comment by maxnordlund** [comment]
Yeah, that may not have been the greatest example, for reference the [project](https://github.com/maxnordlund/future) I was working on uses promises heavily on the inside and I had to do multiple async assertions, which is perhaps a better use for `async`/`await`.

**Comment by maxnordlund** [comment]
OK, it's on [npm](https://www.npmjs.com/package/chai-and-then), I just have to flesh out the README, but it's good to go otherwise.
