### ISSUE TITLE
Not working... for me?

### ISSUE THREAD

**Issue by marcoscaceres** [domenic/chai-as-promised#158]
Following the installation steps in the README, and then running `mocha testfile.js` on throws:

`TypeError: Cannot read property 'eventually' of undefined`

Given testfile.js: 
```JS
"use strict";
var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);

describe("Promise API", () => {
  it("allows us to resolve promises with different values", ()=>{
    Promise.resolve(2 + 2).should.eventually.equal(4);
  });
});
```

It's not clear to me what I'm doing wrong?

**Comment by domenic** [comment]
You forgot `return`. Also, that test look like it will pass, so nothing will happen.

**Comment by domenic** [comment]
Sorry, I didn't read your post closely. I don't see why you would get a TypeError. Hmm...

**Comment by domenic** [comment]
Ah, you forgot `chai.should()` to turn on `should` mode.

**Comment by marcoscaceres** [comment]
ok, trying... should update the docs also in the install section?

**Comment by domenic** [comment]
Yeah, that's more a general Chai thing, since you might pick expect or assert instead, but maybe we should include a "don't forget to do one of those things" note.





On Wed, Jun 29, 2016 at 2:43 AM -0400, "Marcos Cáceres" <notifications@github.com<mailto:notifications@github.com>> wrote:


ok, trying... should update the docs also in the install section?

-

**Comment by marcoscaceres** [comment]
Yeah, otherwise it's kinda confusing. Like the return thing is also misleading because in the example it looks like you can do:

```JS
  // False positives! 
  it("allows us to resolve promises with different values", ()=>{
      Promise.resolve(2 + 2).should.eventually.equal(5);
      Promise.resolve(2 + 2).should.eventually.equal(5);
      Promise.resolve(2 + 2).should.eventually.equal(5);
  });
```

**Comment by marcoscaceres** [comment]
I would strongly urge you to wrap the documentation in describe() and/or it()

**Comment by domenic** [comment]
This library is not Mocha specific though.

**Comment by marcoscaceres** [comment]
@domenic, fair enough. Thanks for your help.
