### ISSUE TITLE
Is there a way to test if a promise object calls a function

### ISSUE THREAD

**Issue by Kannaj** [domenic/chai-as-promised#165]
I'm trying to test a function which doesnt return anything but executes a callback

```js
export const project_list = function(data,res){
  return db.any(queries.ProjectList)
    .then(function(results){
      let newResults = project_list_cleaner(results)
      res(null,newResults)
    })
    .catch(function(err){
      res(err)
    })
}
```

I did try 
```
  it('should retrieve a list',function(){
    return expect(project_list(data,res)).to.eventually.be.false
  })
```

but it fails correctly because the function does not return anything but executes the callback. 
Is there a way i can check if the promise executes the given callback?

Thanks,

**Comment by domenic** [comment]
It sounds like you are not looking for a library that tests promises, but instead a library that tests Node-style callbacks. No, that is not what this library is for.
