### ISSUE TITLE
Dropping UMD module format was a bad decision

### ISSUE THREAD

**Issue by Dynalon** [domenic/chai-as-promised#171]
I just found out you dropped the UMD format in favour of strict CommonJS format. In the docs you tell to rely on browserify (or webpack for that matter). I had to pinned chai-as-promised to `5.3.0` to avoid that change in my test environment and want to encourage you to bring it back.

It is not always feasible to use webpack/browserify for you tests. I.e. I use karma to test isomorphic code  in various browsers, not only for the sake of making sure they work in the browser (as opposed to my node.js tests using mocha where commonjs is used) but also to make sure my UMD bundles work - it is sort of an integration test thing. Still a lot of users don't use webpack/systemJS but rather include `<script>` tags to add my library and access it via a global variable. Thats why in the karma test run, I have to make sure this works and all tests execute successfully. In the past various bugs in webpack have resulted in breaking this kind of inclusion.

Please think about bringing back a chai-as-promised UMD bundle - those could co-exist with a commonJS approach and be created by webpack automatically.

**Comment by domenic** [comment]
Sorry, I'm not interested in doing that. The maintenance burden on me as an open-source maintainer was too high; it is not worth my time to continue working on this library with that requirement. You're welcome to maintain your own fork if you don't like using tools for the reasons you list.
