### ISSUE TITLE
transformAsserterArgs shared across tests?

### ISSUE THREAD

**Issue by ZebraFlesh** [domenic/chai-as-promised#172]
It looks like if you're using es6 modules, import chai-as-promised in more than one place, and then set `chaiAsPromised.transformAsserterArgs` in more than one place, chai-as-promised gets confused and shares the different transformers across test suites. This was very unexpected behavior. I couldn't even achieve test suite isolation even by moving the setup of `transformAsserterArgs` into mocha beforeEach/afterEach hooks.

**Comment by domenic** [comment]
ES6 modules are not supported with chai-as-promised, since they do not work in browsers or in Node.js.

**Comment by ZebraFlesh** [comment]
If you're using mocha and have multiple test suites (`describe`), is it possible to leverage different definitions for `transformAsserterArgs`?

**Comment by domenic** [comment]
Sure, set them up in your `beforeEach` block or similar.
