### ISSUE TITLE
expect(null).to.be.fullfilled succeeds?!

### ISSUE THREAD

**Issue by jakubholynet** [domenic/chai-as-promised#174]
With cha-as-promised 6.0.0 and Chai 3.5.0, this test will pass: 

```js
return expect(null).to.be.fullfilled;
```

I expect it to fail because null is not a Promise and code that expects to get a promise but gets null instead will fail, even if the test is perfectly happy with it. I thing that `.to.be.fullfilled` / `rejected` / `.eventually...` should check that the argument is a promise and fail if it isn't. Using these assertions for non-promises makes no sense and thing it would be very wasteful to force all users to always combine these with `.is.a(Promise)`.

Thanks!

**Comment by ruiquelhas** [comment]
Assuming there are no "unintentional" typos in your example, `fullfilled` should be `fulfilled` instead. This also happened to me btw. That's one of the issues of having assertions as properties instead of methods (no feedback for misused APIs).

**Comment by keithamus** [comment]
Thanks for the issue @jakubholynet - hopefully @ruiquelhas' solution is what you're after.

FWIW Chai 4 goes part way to fixing this by failing on undefined properties (e.g. `fullfilled`, `ture`, `exsit` etc) with a suitable error and a _did-you-mean_ style suggestion. You can try chai 4 by installing `npm i chai@canary`. 

I think given @ruiquelhas's comment and the fixes to chai 4, I'll close this one. Feel free to continue discussing this and if you experience any other issues please do raise them!
