### ISSUE TITLE
Promise.all not checking all promise

### ISSUE THREAD

**Issue by uyadu** [domenic/chai-as-promised#175]
I have a scenario where have to check four assertion , Kept negative condition for one of the assertion(first one)  and expecting test step to be failed  ,but its not happening

 return Promise.all([
         expect(browser.driver.findElement(by.css(enterprisePlan)).isDisplayed()).to.eventually.be.false,
         expect(browser.driver.findElement(by.css(businessPlan)).isDisplayed()).to.eventually.be.true,
         expect(browser.driver.findElement(by.css(personalSignUp)).isDisplayed()).to.eventually.be.true,   expect(browser.driver.findElement(by.css('#u25134>p')).isDisplayed()).to.eventually.be.true.and.notify(done)
 ]);

Could someone help what I am missing here

**Comment by meeber** [comment]
@uyadu Assuming you're using Mocha: I think you just need to get rid of the `.notify(done)` on the fourth assertion (and don't provide a `done` parameter in the `it` block for this test either). The fact that you're returning the `Promise.all` is enough for the test runner to know to wait until the outer promise resolves.

**Comment by glebec** [comment]
Yep. In fact both using `done` and `return`ing a promise is "over-specifying" a mocha spec and fails in recent versions of Mocha. Stick with one approach per `it`.

**Comment by uyadu** [comment]
Thank you @meeber , @glebec  ,it worked for me.
