### ISSUE TITLE
Readme browser notice might want to loosen up on Phantom 2.X

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [domenic/chai-as-promised#180]
Since #77 was resolved, PhantomJS 2.X has become standard. It might make sense to explicitly say that 1.X and below isn't supported, rather than all of Phantom.

**Comment by domenic** [comment]
Since we don't test on PhantomJS in CI, and it's historically been a troublesome platform, it's still not supported. If people get it work, OK, but it's not something that you can open issues asking for help debugging.

**Comment by ptitjes** [comment]
You should indeed test PhantomJS in CI because it looks like `chai-as-promised > 6` makes PhantomJS crash. (And `chai 4.1.2` alone does not btw). We are forced to pin both `chai` and `chai-as-promised`.

**Comment by domenic** [comment]
That's fine; you can do whatever you need to in order to make unsupported stuff work. It's not a priority for this project.
