### ISSUE TITLE
Installation instructions are either wrong or there is a minor bug

### ISSUE THREAD

**Issue by sean256** [domenic/chai-as-promised#181]
Under Installation and Setup -> Node you have the following:

```
var chai = require("chai");
var chaiAsPromised = require("chai-as-promised");

chai.use(chaiAsPromised);

// Then either:
var expect = chai.expect;
// or:
var assert = chai.assert;
// or:
chai.should();
// according to your preference of assertion style
```

I think the bottom should be 

```
// Then either:
var expect = chai.expect;
// or:
var assert = chai.assert;

// and finally:
chai.should();

```

Without the last line I get undefined errors.

**Comment by domenic** [comment]
Please produce an example that uses the expect and assert styles (but not the should style) and gives undefined errors with `chai.should()` omitted.

**Comment by sean256** [comment]
```
'use strict';

const chai = require('chai');
const chaiAsPromised = require("chai-as-promised");
chai.use(chaiAsPromised);
var expect = chai.expect;

//chai.should(); //uncomment to make it work

function someAsyncThing(){
	return new Promise((resolve,reject)=>{
		setTimeout(()=>{
			resolve('all done');
		},100)
	});
}

it("should be fulfilled", function () {
	someAsyncThing().should.eventually.equal('all done')
});
```

This results in:
`TypeError: Cannot read property 'eventually' of undefined`

**Comment by meeber** [comment]
@sean256 In your example, you're using Chai's `should` syntax, so yes you do need `chai.should()`, but you don't need `var expect = chai.expect`.

Alternatively, you can use Chai's `expect` syntax in which case you need `var expect = chai.expect` but you don't need `chai.should()`. Example:

```js
expect(someAsyncThing()).to.eventually.equal('all done');
```

**Comment by domenic** [comment]
Yep. This is working exactly as the documentation states.
