### ISSUE TITLE
Trouble with promises elsewhere in the code being tested

### ISSUE THREAD

**Issue by pwhipp** [domenic/chai-as-promised#182]
I have a redux app using redux-thunk where some action functions are defined as follows:
```
export const addObject = (object) => {return {type: 'ADD_OBJECT', object}};
export const syncObject = (objectId) =>
    (dispatch, getState) => {
      dispatch({type: 'SYNC_OBJECT', id: objectId});
      getState().config.ajax.get('untyped/' + objectId + '/').then(
          (object) => dispatch(addObject(object)))};
```
In the real store the ajax object accesses a remote service. In the test it is redefined thus:

```
// Set up a dummy ajax config for sync objects
const ajax = {
  result: {},
  get: (url) => Promise.resolve(ajax.result)};

store.dispatch(actions.setConfig('ajax', ajax));

describe('redux: sync objects', () => {
  it('syncs an object', () => {
    const tom = {id: 'tom', age: 4};
    store.dispatch(actions.addObject(tom));
    assert.isOk(store.getState().objects.map.tom.age === 4, 'tom is 4');

    ajax.result = {id: 'tom', age: 5};
    store.dispatch(actions.syncObject('tom'));
    assert.eventually.equal(Promise.resolve(null).then(() => store.getState().objects.map.tom.age), 5, 'tom is now 5 as a result of sync')
  })
});
```

In the `eventually` assertion, I had to wrap the contrived promise around the desired result to ensure it is synchronized late enough in the day for the assertion to pass. If this is not done, the test fails because the promise in the action resolves after the test completes.

Is there a better way to do this?

**Comment by keithamus** [comment]
@pwhipp thanks for the issue. You either need to `return` the assertion that has `eventually`, or alternatively add the `done` argument to your `it` and chain `.and.notify(done)` to the end of the `eventually` assertion. More about this [on the mocha website](https://mochajs.org/#asynchronous-code) and [and in the readme](https://github.com/domenic/chai-as-promised#working-with-non-promisefriendly-test-runners).

I'll close this for now. If you run into more problems let us know and we can perhaps reopen this issue.
