### ISSUE TITLE
ReferenceError: Can't find variable: require

### ISSUE THREAD

**Issue by elewin** [domenic/chai-as-promised#183]
I have everything up and running just fine using Karma/Mocha/Chai by itself, but when I try to add chai-as-promised (along with karma-chai-as-promised) I keep running into this wall:

```
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at node_modules/chai-as-promised/lib/chai-as-promised.js:2
```

the line that it seems to be failing on in chai-as-promised.js is

`
var checkError = require("check-error");
`

I've tried adding Browserify and Karma-Browserify, but I still get the same issue. Is there some other pre-requisite I need? 

It does this with Chrome as well:
```
Chrome 56.0.2924 (Windows 8.1 0.0.0) ERROR
  Uncaught ReferenceError: require is not defined
  at node_modules/chai-as-promised/lib/chai-as-promised.js:2
```

**Comment by werwolfby** [comment]
The same issues for me, and I can't find any workaround for this

**Comment by werwolfby** [comment]
And according to the documentation:

Chai as Promised is only compatible with modern browsers (IE ≥9, Safari ≥6, no PhantomJS).

So my issues was that I've tried to run it under PhantomJS.
I'm still trying to find solution with some browserify plugin for chai-as-promise module

**Comment by elewin** [comment]
This doesn't appear to be a phantom issue as it does the exact same thing with Chrome

**Comment by werwolfby** [comment]
Yep, this is not a PhantoJS issue, it is because `chai-as-promised` implemented as ES6 module, which doesn't have require method.

So I fixed the issue by load module directly in karma entry point file:

```
import chai from 'chai'
import chaiAsPromised from 'chai-as-promised'

chai.use(chaiAsPromised)
```
But `expect` was not loaded globally (and I don't know how to fix it)
And in tests where I need `chai-as-promised` assertions I'm using:
```
import { expect } from 'chai'
```

So I'm not using `karma-chai-as-promised`. When I tried it, I felt into the same issues.
So I hope my workaround will help you.

**Comment by elewin** [comment]
It looks like the require line is not in version 5.x, so you can use that one for now, but I am still curious how to get it to work with version 6.x and any future versions

**Comment by werwolfby** [comment]
Over any browserify transpilers

**Comment by domenic** [comment]
From the readme:

> To use Chai as Promised in environments that don't support Node.js-like CommonJS modules, you'll need to use a bundling tool like browserify. See also the note below about browser compatibility.

**Comment by michaelgallaghertw** [comment]
I use karma + webpack + karma-chai-as-promised and I'm getting this error
