### ISSUE TITLE
chai-as-promised 6.0.0is incompatible with chai 4.0.0

### ISSUE THREAD

**Issue by jlin412** [domenic/chai-as-promised#184]
We are using chai-as-promised 6.0.0 with chai 4.0.0 with protractor and cucumber in typescript.
It seems that it is failing at the next scenario when expectation is failed.
With chai 3.4.1, chai-as-promised is working as expected.

**Comment by meeber** [comment]
Hi @jlin412. There's currently only a canary release of Chai v4. Once it's officially released, chai-as-promised will (presumably) be updated to accommodate the breaking changes. There's a WIP PR (#157) for this purpose.

**Comment by victorperin** [comment]
Chai 4.0.0 is now in production and now I'm having issues with this package too.

**Comment by keithamus** [comment]
Thanks @jlin412 and @victorperin. We're currently tracking this through #157. I'll close this one for now, if you'd like to get updates on this - you should subscribe to that issue.
