### ISSUE TITLE
Chai-as-promised-- TypeError: 'xxxx' is not a thenable.

### ISSUE THREAD

**Issue by nanichandu84** [domenic/chai-as-promised#188]
Hi,

I am using chai-as-promised, expect for the assertions. I am getting weird error with the assertions. Please have a look at the below code,

     expect(flowname).to.eql(params.flow.flowName).notify(done);

The above code should pass, as both the expected value and actual as same. But instead I am getting, TypeError: 'Auto_flow_d5xybt' is not a thenable.

If I make the above expect statement fail, like

    expect(flowname).to.eql(params.flow.flowDesc).notify(done);

Then I am getting the proper assertion error, expected value is not equal to actual value.

Why I am getting thenable error when the expected and actual values are same?

Any help is much appreciated. 

Thanks in advance.

**Comment by domenic** [comment]
Probably because you are using `.notify(done)` on something that is not a thenable.
