### ISSUE TITLE
Chai-as-promised and mocha timeout

### ISSUE THREAD

**Issue by vinhboy** [domenic/chai-as-promised#190]
With mocha having a default timeout of 2000ms, this test would fail

```
    it('expected to be fulfilled', function (done) {
      var fooBar = new Promise((resolve, reject) => {
        setTimeout(function(){
          resolve();
        }, 2001);
      });
      expect(fooBar).to.be.fulfilled.notify(done);
    });

```

Output:

```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

I can fix this by using setting `this.timeout(0);`

Would it make sense for this to be a default with chai-as-promised? I would think a lot of promises will take more than 2000ms.

**Comment by domenic** [comment]
No, I don't think so. There's no reason promises are any different from other asynchronous operations in Mocha. You need to adjust your timeouts accordingly for testing promises just like for testing callbacks or setTimeout or fetch() or anything else.
