### ISSUE TITLE
Error with jquery promise

### ISSUE THREAD

**Issue by techyrajeev** [domenic/chai-as-promised#191]
I am trying to test following code. Basically server rejects this request since some parameter were not sent as required by api specification.
`Api.createRecord` use `jquery.ajax` under the hood and returns a `jquery` promise when called.

```
    describe("Creating test record with incorrect data", ()=> {
        const params      = {tId:"12323","col":"colValue"};
        it('Should not create new record', (done) => {
            const result = Api.createRecord(params);
            console.log(result);
            expect(result)
                .to.eventually.equal(null)
                .notify(done);
        });
    });

```

When I run this code I get following error.

```
   Error: done() invoked with non-Error: {"readyState":0,"status":0,"statusText":"SyntaxError"}
      at mightThrow (node_modules/jquery/dist/jquery.js:3583:29)
      at Window.process (node_modules/jquery/dist/jquery.js:3651:12)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:524:19)

```

I am not able to find out what is the problem. Whether there is some problem in my code or somewhere else.

**Comment by domenic** [comment]
It appears jQuery is rejecting the promise with a non-Error, instead of fulfilling it with null. So the test is failing as expected.

**Comment by techyrajeev** [comment]
This is how I am sending ajax request.
```
    sendRequest(URL, dataToSend) {
        return $.ajax({
            type        : 'POST',
            url         : URL,
            crossDomain : true,
            data        : JSON.stringify(dataToSend),
            dataType    : 'json'
        }).fail((responseData) => {
            if (responseData.responseCode) {
                console.error(responseData.responseCode);
            }
        });
    },

```
is there some problem in above code that it handles failures instead of it getting thrown?

**Comment by domenic** [comment]
I'm not sure, sorry. I don't really have time to debug your codebase. Maybe someone else who is monitoring this issue tracker will, or perhaps you could turn to StackOverflow or your coworkers.

**Comment by techyrajeev** [comment]
In mocha docs I found the solution.

> In Mocha v3.0.0 and newer, returning a Promise and calling done() will result in an exception, as this is generally a mistake:

```
const assert = require('assert');

it('should complete this test', function (done) {
  return new Promise(function (resolve) {
    assert.ok(true);
    resolve();
  })
    .then(done);
});
```

I changed my test case to this one and it worked.

`            expect(result).to.be.rejected;
`
I am really sorry to bother you all the problem was actually at my end only.
