### ISSUE TITLE
typescript and chai-promise

### ISSUE THREAD

**Issue by jmls** [domenic/chai-as-promised#192]
I have a mocha test written in typescript. I am trying to test a promise like so

```javascript
        it('should get data if using valid credentials', () => {
            let result = Project.find({token:"validToken"});
            return expect(result).to.eventually.equal(projectAllResponse);
        });
```
the typescript compiler complains about `Property 'eventually' does not exist on type 'Assertion'.`

the `Project.find()` function does return a promise, as this test works :
```javascript
       it('should get data if using valid credentials', (done) => {
            Project.find({token:"validToken"}).then((data) => {
                expect(data).to.equal(projectAllResponse);
                done()
            })
        });
```
I am curious to know what the issue here may be ? I have installed `@types/chai-as-promised` and the relevant @types{mocha, chai etc)

thanks

**Comment by domenic** [comment]
I don't have any idea about third-party tools like TypeScript myself, but maybe someone else on the issue tracker can help, so I'll leave this open for a few days, even though it's not an issue with chai-as-promised.

**Comment by kittaakos** [comment]
@jmls I think you do not need `expect` since your `result` is a promise. Could please try this?

```
import * as chai from "chai";
import * as chaiAsPromised from "chai-as-promised";

before(() => {
    chai.should();
    chai.use(chaiAsPromised);
});

namespace Project {
    export function find(arg: { token: string }): Promise<boolean> {
        return new Promise<boolean>((resolve, reject) => {
            if (arg && arg.token === "validToken") {
                return resolve(true);
            }
            reject(new Error(`Was an invalid token.`));
        })
    }
}

describe("bla", () => {

    it("fail", () => {
        return Project.find({ token: "invalidToken" }).should.eventually.be.rejectedWith(Error);
    });

    it("pass", () => {
        return Project.find({ token: "validToken" }).should.eventually.be.true;
    });

});
```

**Comment by mothershipper** [comment]
I had this issue today and banged my head against the wall for a while.

You need to install the community supported typings, available at `@types/chai-as-promised`.  `yarn add --dev @types/chai-as-promised`.

Once I installed those, I then had to init chai-as-promised as follows:

```javascript
import { use } from 'chai';
use(require('chai-as-promised')) 
```
I'm not entirely sure what's going on here, but it seems that chai-as-promised is not compatible with the `import` syntax, or at least not in a way understood by typescript after adding the typings.

**Comment by pollen8** [comment]
it probably depends on your Typescript settings - I have `esModuleInterop` and `allowSyntheticDefaultImports` to be true, then import works ok for me

**Comment by mothershipper** [comment]
Thanks @pollen8, I'll check those flags out -- this is my first foray into typescript and it's been several years since I've worked primarily in JS, lots to catch up on in the ecosystem!
