### ISSUE TITLE
sinon js stub.resolves not working with chai-as-promised.

### ISSUE THREAD

**Issue by gx761** [domenic/chai-as-promised#193]
I'm using sinon 2.2.0 which provides stub.resolves function to return a resolved promise. However it always gives me an timeout error. 

However, it does work with stub.yields(). I don't know what's going on here. The stub.resolves() function makes more sense semantically, and i really want to use that to handle stub returns promise.

**Comment by mattbishop** [comment]
A nice test case would help here @gx761
