### ISSUE TITLE
how to wrap "async" function

### ISSUE THREAD

**Issue by shaunc** [domenic/chai-as-promised#194]
Environment:
node 7.10.0, babel config:
```
{
 "presets": [ 
    ["env", {
      "targets": {"node": "current"},
      "exclude": [
        "transform-async-to-generator"
      ]
    }]
  ]
}
```
(so using native "async/wait")

I want to "expect" that an async function when called, will eventually throw foo. However, `expect` will not wrap an async function:

    async function foo() {
      await Promise.resolve(1)
      throw new Error('foo')
    }
    expect(foo).to.eventually.throw('foo')

Gives me:

```
/Volumes/Macintosh_HD/Users/shauncutts/src/gabbage/node_modules/chai-as-promised/lib/chai-as-promised.js:29
            throw new TypeError(utils.inspect(assertion._obj) + " is not a thenable.");
```
Given that its a native async/await, it should be able to detect this, right? (indeed, expect without chai-as-promised gives me the error: `AssertionError: expected [Function] to be a function`.)

I know I can work around this pretty easily, but I thought I'd ask, since chai-as-promised is all about having an idiomatic way to treat asynchronous behavior.

**Comment by domenic** [comment]
Async functions don't throw; they return rejected promises. So you should say

```js
expect(foo()).to.be.rejectedWith('foo');
```

**Comment by shaunc** [comment]
ok ... fair enough -- (thanks for the quick reply!). 

I was thinking that the idea is to preserve parallelism with normal expect behavior: normally expect recognizes a function, then, when it gets "throw()" at end of chain, it calls it to see if it throws. I would think the parallel would be, with an asynchronous function and `eventually.throws`, to call it and see if it eventually throws. 

Of course this isn't necessary at all as you point out since for normal function you need to delay, while async is after all asynchronous. Just thought it would be good to have the same interface to wrap any callable.

**Comment by dmwelch** [comment]
Can I propose this example be added to the docs?

**Comment by domenic** [comment]
rejectedWith is already in the docs...
