### ISSUE TITLE
chai-as-promised@6.0.0 requires a peer of chai@>= 2.1.2 < 4 but none was installed.

### ISSUE THREAD

**Issue by kacpe-r** [domenic/chai-as-promised#195]
Hi there.
4 days ago had been released new version of chai (v4.0.0).
I took a look into it and it has several breaking changes.
Unfortunately, chai-as-promised requires a chai in <4 version.
Do you consider upgrading your library?
Regards,
Kacper

**Comment by keithamus** [comment]
Thanks for this @kacpe-r. We're currently tracking this through https://github.com/domenic/chai-as-promised/pull/157. I'll close this one for now, if you'd like to get updates on this - you should subscribe to that issue.
