### ISSUE TITLE
Allow Chai 4.0.0 as a valid peerDependency

### ISSUE THREAD

**Issue by moberemk** [domenic/chai-as-promised#197]
Current trying to upgrade to Chai 4 causes the following NPM error:

```
npm WARN chai-as-promised@6.0.0 requires a peer of chai@>= 2.1.2 < 4 but none was installed.
```

Can the library be updated to allow Chai 4 as a valid peerDep?

**Comment by keithamus** [comment]
Thanks for this @moberemk. We're currently tracking this through #157. I'll close this one for now, if you'd like to get updates on this - you should subscribe to that issue.

**Comment by moberemk** [comment]
Ah, sorry, I missed that issue earlier--thanks for the link, will follow that issue instead.
