### ISSUE TITLE
Provide CDN-ready files

### ISSUE THREAD

**Issue by dakshshah96** [domenic/chai-as-promised#199]
Hey @domenic,

I'd like to host your library, chai-as-promised on [cdnjs](https://github.com/cdnjs/cdnjs) — It is one of the most famous free and public web front-end CDN services which is used by [~1,143,000 websites](https://trends.builtwith.com/cdn/CDN-JS) worldwide.

While going through the repository for files to be hosted, I couldn't find any files which can be directly used in the browser.

Is it possible to provide those files in the project so we can add your library to cdnjs?

https://github.com/cdnjs/cdnjs/pull/11281

**Comment by domenic** [comment]
Sorry, no, the library is meant to be used via CommonJS. If you need something browser-ready, use a project like browserify.
