### ISSUE TITLE
Suggestion: documentation should say when .eventually. should not be used

### ISSUE THREAD

**Issue by paul-hammant** [domenic/chai-as-promised#201]
"Eventually" has a temporal connotation. e.g. "Div has text of 'saved' after 5 seconds".

As the Gmail editor does:

![2017-06-09_0725](https://user-images.githubusercontent.com/82182/26973603-4529f986-4ce5-11e7-8eb9-bcbbbfb25df1.png)

The documentation should state clearly that 'eventually' should not be used if the thing being operated on doesn't have something that will happen after a delay, or stops happening after a delay. With the delaying being a changeable period of time.

**Comment by domenic** [comment]
eventually doesn't have anything to do with delays or Gmail. All it is is a chainer that promisifies all the other Chai assertions. The docs are very explicit about this:

> With it, you can transform any existing Chai assertion into one that acts on a promise:

**Comment by paul-hammant** [comment]
Gmail was just an example web-app that leverages asynchronous activity. Noobs may misunderstand the intention. Eventually definitely has temporal connotations.  Of course I'm only new you your tech. I co-created Selenium v1, and look after https://github.com/SeleniumHQ/fluent-selenium (Java) these days with has a within() and a without() method to allow for the fluent traversal of a page to and a changeable DOM over time, just fine :)
