### ISSUE TITLE
Using expect for notify?

### ISSUE THREAD

**Issue by tamj0rd2** [domenic/chai-as-promised#203]
Is it possible to use the below code snippet with the expect syntax?

```js
it("should change the state", function (done) {
    otherState.should.equal("before");
    promise.should.be.fulfilled.then(function () {
        otherState.should.equal("after");
    }).should.notify(done);
});
```

All of my tests have been using expect so far, so I'd prefer not to change it if possible. I get the error `TypeError: (0 , _chai.expect)(...).to.be.fulfilled.then is not a function` if I try to use the expect syntax. My code:

```js
it('does a thing', done => {
  let promise = wrapper.instance().handleSubmit(new Event('submit')) // just returns a promise
  expect(promise).to.be.fulfilled.then(() => {
    // my expectations
  }).and.notify(done)
})
```

So I tried to use the should syntax instead but I get the error `TypeError: promise.should.be.fulfilled.then is not a function`

```js
it('does a thing', done => {
  let promise = wrapper.instance().handleSubmit(new Event('submit')) // just a function that returns a promise
  promise.should.be.fulfilled.then(() => {
    // my expectations...
  }).should.notify(done)
})
```

**Comment by meeber** [comment]
Few things:

1. You should not be getting that error message regardless. Something else is going on in your code or test suite. I'm not sure what.
2. Even if everything else was working correctly, only `.should.notify` would be able to follow up a `.fulfilled.then` in that way. 
3. I'd recommend just returning the promise instead, like the below example (which I've tested).

```js
const chai = require("chai");
const chaiAsPromised = require("chai-as-promised");

chai.use(chaiAsPromised);

const expect = chai.expect;

it("meow", () => {
  let promise = Promise.resolve();
  return expect(promise).to.be.fulfilled.then(() => {
    expect(42).to.equal(42);
  });
});
```

**Comment by tamj0rd2** [comment]
@meeber I'm really not sure what's going on. At the top of my code I've put the following, but I'm still getting errors saying to.be.fulfilled is not a function

```js
import chai, { expect } from 'chai'
import chaiAsPromised from 'chai-as-promised'
chai.use(chaiAsPromised)```

**Comment by tamj0rd2** [comment]
Even if I use `require()` instead of import, it still doesn't work

**Comment by tamj0rd2** [comment]
I've just noticed the following when I run `npm ls --depth=0`

UNMET PEER DEPENDENCY chai@4.0.2
npm ERR! peer dep missing: chai@>= 2.1.2 < 4, required by chai-as-promised@6.0.0

I have chai 4.0.2 installed but chai-as-promised thinks it's missing?

**Comment by meeber** [comment]
chai-as-promised doesn't support Chai 4 yet (see #157). You can use chai@3.5 instead.

**Comment by tamj0rd2** [comment]
@meeber Ahh, thank you!

**Comment by nic-hartley** [comment]
Does chai-as-promised support Chai 4 yet?
