### ISSUE TITLE
chai-as-promised@7 with Karma: reserved word 'let'

### ISSUE THREAD

**Issue by haraldrudell** [domenic/chai-as-promised#207]
I am not sure if there is a transpile required or a refrain from fancy new constructs.

Here is the error message:
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Use of reserved word 'let' in strict mode
  at node_modules/chai-as-promised/lib/chai-as-promised.js:3

Get-around:
npm install chai@3 chai-as-promised@5
-> 3.5.0 + 5.3.0

**Comment by domenic** [comment]
See https://github.com/domenic/chai-as-promised#browsernode-compatibility

**Comment by haraldrudell** [comment]
So chai cannot be upgraded until Karma uses the not-yet-released Phantom 2.5?
https://github.com/ariya/phantomjs/issues/14458

**Comment by domenic** [comment]
Did you read the section I linked?

> If your browser doesn't support modern JavaScript syntax, you'll need to transpile it down using a tool like Babel.

**Comment by haraldrudell** [comment]
So, the solution is to add to the karma config object, a rule inside the webpack field module.rules making the babel-loader process with the test:
        test: require.resolve('chai-as-promised'),

**Comment by baywet** [comment]
In my case I don't have control over the webpack config or most of the pipeline. I ended up reverting to 6.0.0 until phantomjs fully supports es6/2015
https://github.com/ariya/phantomjs/issues/14506

**Comment by aldencolerain** [comment]
If you want more detail on how to do this with Karma Webpack and PhantomJS 5 checkout my comment on the Vue.js issue: https://github.com/vuejs-templates/webpack/issues/646#issuecomment-329324092
Thanks @haraldrudell for the solution.

**Comment by mancioshell** [comment]
@haraldrudell i have added your advised configuration in my karma.conf.js, but it still not work, with the same error
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  SyntaxError: Use of reserved word 'let' in strict mode

Could you post your solutions please?

Thanks in advance
