### ISSUE TITLE
for..of is not IE11 compatible

### ISSUE THREAD

**Issue by ianwremmel** [domenic/chai-as-promised#209]
https://kangax.github.io/compat-table/es6/#ie11

While I appreciate the desire to write modern JavaScript, IE11 is going to have to be "modern" through something like 2020 thanks to the Microsoft support cycle. Transpilers work pretty hard to prevent altering node modules, so the following statement is a lot more complex for most of us than it reads. 

> Chai as Promised requires Node v4+ or a browser with equivalent support for modern JavaScript syntax. If your browser doesn't support modern JavaScript syntax, you'll need to transpile it down using a tool like Babel.

Would you be will to produce a browser bundle with support for current browsers?

**Comment by domenic** [comment]
No; please feel free to use whatever tools are appropriate for your project and environment, but that's specific to you, and won't be a part of this library.
