### ISSUE TITLE
Ensure ES5 compatibility

### ISSUE THREAD

**Issue by lukastaegert** [domenic/chai-as-promised#211]
To ensure cross-browser compatibility, we have a large suite of Karma tests that we run in both Safari 9 and IE11. Unfortunately, recent changes to your code (e.g. "let" etc.) break compatibility with these browsers.

Of course we could transpile your library but it would be preferable if your library was provided in an ES5 compatible way especially considering that for now, this seems to be the accepted standard for npm libraries, cf. [how to provide untranspiled ES6 code](http://2ality.com/2017/06/pkg-esnext.html)

Thanks in advance,
Lukas

**Comment by domenic** [comment]
Sorry, no, I'm not interested in maintaining this library for old browsers. See the readme, and please transpile as appropriate for your project. Pushing the maintenance burden on me is not something I'm interested in.
