### ISSUE TITLE
Issue with parsing promises that return arrays with expect(actual) vs. actual.should

### ISSUE THREAD

**Issue by weijie-tang** [domenic/chai-as-promised#213]
When parsing the values of an array returned by a promise, I get weird behavior with the use of actual.should vs. expect(actual).

Given the following versions of chai, chai-things, chai-as-promised and typescript:

```typescript
+-- types@chai@3.5.2
+-- types@chai-as-promised@0.0.30
+-- chai@3.5.0
+-- chai-as-promised@6.0.0
+-- typescript@2.4.1
```

And the following import order:

```typescript
import chai = require('chai');
chai.use(require('chai-as-promised'));
const expect = chai.expect;
```

And the following assertions:

```typescript
expect(Promise.resolve([{ test: 'test' }])).to.eventually.have.length(1);
Promise.resolve([{ test: 'test' }]).should.eventually.have.length(1);
```

The former works without issue, but the second one returns the following result:

```
(result: FAILURE, error:TypeError: Cannot read property 'eventually' of undefined)
```

**Comment by domenic** [comment]
As with all Chai plugins, to actually install the `should` property, you need to do `chai.should()`. See https://github.com/domenic/chai-as-promised
