### ISSUE TITLE
Promise rejection not failing unit test

### ISSUE THREAD

**Issue by adityasharma2057** [domenic/chai-as-promised#217]
I'm still seeing the issue where a promise, if rejected, will not fail the unit test

```
const servicePromise = service.setRouteCharges(); //Returns a rejected promise
servicePromise.should.be.fulfilled;
```

If the promise is rejected when i expect it to be resolved, it doesn't fail the Unit Test. Rather, gives a warning "**UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2)........** " and passes the unit test.

Was under the impression this has been fixed already, apparently not. 

I'm using:
_"chai": "^4.1.2",
"chai-as-promised": "^7.1.1",
Node: v8.3.0_

**Comment by domenic** [comment]
It looks like you are forgetting to return the promise, per the README.

**Comment by adityasharma2057** [comment]
My bad. Thanks for the prompt reply. Ended up using it this way:

```
return servicePromise.should.be.fulfilled.then(() => {
            assert.equal(route.Commissions.length, 0);
            assert.equal(route.Fees.length, 0);
        });
```

I'll close the issue.
