### ISSUE TITLE
Invalid Chai property: catch.

### ISSUE THREAD

**Issue by sebastianst** [domenic/chai-as-promised#220]
In my node application, I assert a rejection of a promise with the following code:
```javascript
return promise.should.be.rejected;
```
which throws the error:
```
Error: Invalid Chai property: catch. Did you mean "match"?
      at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:63:17)
      at Context.sync (node_modules/mocha-steps/lib/step.js:30:61)
```
I can also change `.rejected` to `.fulfilled`, which shows the same error.
The promise throws an error if called normally, which is what I want to assert here.

Running with chai 4.1.2, chai-as-promised 7.1.1, node 8.4.0

Any ideas?

**Comment by domenic** [comment]
Chai as Promised doesn't even appear in that stack trace, so I'm not sure your problem is even with this repository. Can you provide a complete, *minimal* example that I can run with `node example.js`

**Comment by meeber** [comment]
@sebastianst Looks like a bad interaction between Chai core's proxy protection feature and the `mocha-steps` library when returning promises.

In the short term, you can resolve the issue by adding this to the top of your tests:

```js
chai.config.proxyExcludedKeys.push('catch');
```

It may also be worth raising an issue in Chai's issue tracker to have `catch` permanently added as an exception on [this line](https://github.com/chaijs/chai/blob/0d19b3518265ba0ff17689a3ae1dc7e7b6c6bf16/lib/chai/config.js#L93).

**Comment by sebastianst** [comment]
@meeber Awesome, that worked! It was indeed the interplay of steps and Promises that made it fail. I'll post an issue to Chai about it.
