### ISSUE TITLE
`.to.be.eventually.typo` should crash

### ISSUE THREAD

**Issue by anderson-otuka-dextra** [domenic/chai-as-promised#224]
The current test should crash on all 4 `crashes on typo`, but it does not.
```js
describe('Typo Test', () => {
  context('with resolved promises', () => {
    const promise = new Promise(resolve => setTimeout(resolve, 9))
    it('works on success',  () => expect(promise).to.be.eventually.fulfilled)
    it('crashes on typo 1', () => expect(promise).to.be.eventually.fullfilled)
    it('crashes on typo 2', () => expect(promise).to.be.eventually.rejeced)
  })
  context('with rejected promises', () => {
    const promise = new Promise((r, reject) => setTimeout(() => reject(new Error(''), 9)))
    it('works on success',  () => expect(promise).to.be.eventually.rejected)
    it('crashes on typo 3', () => expect(promise).to.be.eventually.rejeced)
    it('crashes on typo 4', () => expect(promise).to.be.eventually.fullfilled)
  })
})
```
Actually, I can type any word after a connector / `expect`, and the word gets "gracefully" ignored, like:
```
expect(promise).anything
expect(promise).to.anything
expect(promise).to.be.anything
expect(promise).to.be.eventually.anything
```
This is much error-prone.

**Comment by meeber** [comment]
@anderson-otuka-dextra Which Node and library versions are you using? Here's what I get with `node v8.6.0`, `chai 4.1.2`, and `chai-as-promised 7.1.1`:

>   1) Typo Test with resolved promises crashes on typo 1:
>      Error: Invalid Chai property: fullfilled. Did you mean "fulfilled"?
>       at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:63:17)
>       at Context.it (test/index.js:11:67)
> 
>   2) Typo Test with resolved promises crashes on typo 2:
>      Error: Invalid Chai property: rejeced. Did you mean "rejected"?
>       at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:63:17)
>       at Context.it (test/index.js:12:67)
> 
>   3) Typo Test with rejected promises crashes on typo 3:
>      Error: Invalid Chai property: rejeced. Did you mean "rejected"?
>       at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:63:17)
>       at Context.it (test/index.js:17:67)
> 
>   4) Typo Test with rejected promises crashes on typo 4:
>      Error: Invalid Chai property: fullfilled. Did you mean "fulfilled"?
>       at Object.proxyGetter [as get] (node_modules/chai/lib/chai/utils/proxify.js:63:17)
>       at Context.it (test/index.js:18:67)

For this to work, the javascript environment needs to support ES6 Proxies, and Chai needs to be at least v4.

**Comment by anderson-otuka-dextra** [comment]
@meeber you are right. I was using `node v8.4.0`, `chai 3.5.0` and `chai-as-promised 7.1.1`.
Thanks for the quick answer!
