### ISSUE TITLE
isRejected not working with optional message inside of Promise.all

### ISSUE THREAD

**Issue by andyjac** [domenic/chai-as-promised#228]
__node:__ `7.5.0`
__mocha:__ `4.0.1`
__chai:__ `4.1.2`
__chai-as-promised:__ `7.1.1`

I apologize if this issue has already been documented elsewhere and I missed it.

I am running the following code and am seeing some unexpected results:

```
let mocha = require('mocha');
let chai = require('chai');
let chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);

let assert = chai.assert;

describe('test example', () => {
  it('should pass without a message', () => {
    assert.isRejected(Promise.reject());
  });
  
  it('should pass with a message', () => {
    assert.isRejected(Promise.reject(), 'promise was rejected');
  });
  
  it('should pass without a message inside of Promise.all', () => {
    return Promise.all([
      assert.isRejected(Promise.reject())
    ]);
  });
  
  it('should pass with a message inside of Promise.all', () => {
    return Promise.all([
      assert.isRejected(Promise.reject(), 'promise was rejected')
    ]);
  });
});

```

I would expect all of these to pass, but for some reason the final assert is producing a failure:

```
    test example
    ✓ should pass without a message
    ✓ should pass with a message
(node:38892) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'message' of undefined
(node:38892) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    ✓ should pass without a message inside of Promise.all
    1) should pass with a message inside of Promise.all


  3 passing (17ms)
  1 failing

  1) test example should pass with a message inside of Promise.all:
     TypeError: Cannot read property 'message' of undefined
      at Object.compatibleMessage (node_modules/check-error/index.js:78:70)
      at getBasePromise.then.reason (node_modules/chai-as-promised/lib/chai-as-promised.js:191:77)
      at runMicrotasksCallback (internal/process/next_tick.js:58:5)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by andyjac** [comment]
User error (facepalm). Was not returning the first two asserts. Once I did that the second test failed for the same reason as the fourth. I guess you can no longer pass the message as the second argument instead of the error expectation? Whoops!

**Comment by meeber** [comment]
@andyjac When you provide a second argument to the `assert.isRejected` assertion, the behavior is to assert that the promise was rejected AND the string you provided in the second argument is contained within the error message of the rejected promise. However, the rejected promise in `Promise.reject()` is just `undefined`, so the `check-error` module is trying to see if the message "promise was rejected" is contained inside of the `.message` property of `undefined`, which causes it to choke, since `undefined` has no properties.

For example:

```js
  it('should pass with a message', () => {
    return assert.isRejected(Promise.reject('meow'), 'promise was rejected');
  });
```

>       AssertionError: expected promise to be rejected with an error including 'promise was rejected' but got 'meow'
>       + expected - actual
> 
>       -meow
>       +promise was rejected

**Comment by andyjac** [comment]
@meeber Thanks for the clarification! Probably shoulda read the docs more closely before opening this :P
