### ISSUE TITLE
Not failing tests with incorrect rejectedWith('text')

### ISSUE THREAD

**Issue by Darkbladecr** [domenic/chai-as-promised#232]
I am thankful for the developers and maintainers of this package as it is something that works well with the new async/await syntax. Something that is not done well with other testing packages.

I have one issue with the current setup, in promises that are rejected, but fed the incorrect `error.message` are not causing tests to fail, and instead will cause a soft error:

```
(node:4060) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError: expected promise to be rejected with an error including 'Question not foudn.' but got 'Question not found.'
(node:4060) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Was there a specific reason why not to match these strings. If we only want to check for rejection we can just call `expect(subject).to.be.rejected;`

Surely `.rejectedWith()` should be more strict?

**Comment by Darkbladecr** [comment]
Nevermind, when reading the [test code](https://github.com/domenic/chai-as-promised/blob/master/test/should-promise-specific.js), it actually substrings or you can use regex

**Comment by Darkbladecr** [comment]
Sorry, but it should still fail if the substring or regex doesn't match, as there could be different Error calls that you are testing for!

**Comment by meeber** [comment]
@Darkbladecr Please provide a simple, reproducible example. It shouldn't be behaving the way you've described, so I suspect there's something else going on.

**Comment by Darkbladecr** [comment]
```
// rejected.js
import chai from 'chai';
import chaiAsPromised from 'chai-as-promised';
import 'chai/register-expect';
chai.use(chaiAsPromised);

async function asyncDbCall() {
	try {
		const dbFind = await Promise.resolve(undefined);
		if (!dbFind) {
			throw new Error('Object not found.');
		}
		return;
	} catch (e) {
		throw e;
	}
}

it('rejectedWith not failing', async () => {
	expect(asyncDbCall()).to.be.rejectedWith('Object not found and not failing.');
});

```

Running with `mocha ./rejected.js --require babel-core/register`
Test passes, and console logs:
```
(node:5300) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError: expected promise to be rejected with an error including 'Object not found and not failing.' but got 'Object not found.'
(node:5300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by meeber** [comment]
@Darkbladecr You need to either `await` or `return` the assertion. Without it, Mocha doesn't know to wait for that asynchronous assertion to complete.

**Comment by Darkbladecr** [comment]
Thank you, you are right, the correct code would be either:

```
it('rejectedWith not failing', async () => {
	await expect(asyncDbCall()).to.be.rejectedWith(
		'Object not found and failing'
	);
});
```
or
```
it('rejectedWith not failing', () => {
	return expect(asyncDbCall()).to.be.rejectedWith(
		'Object not found and failing'
	);
});
```
