### ISSUE TITLE
using with chai-exclude

### ISSUE THREAD

**Issue by 95gabor** [domenic/chai-as-promised#233]
Is there a way to use chai-as-promised with [chai-exclude]( https://github.com/mesaugat/chai-exclude)?

I tried the following:
```js
import 'mocha';
import * as chai from 'chai';
import * as chaiAsPromised from 'chai-as-promised';
import chaiExclude = require('chai-exclude');

chai.should();
chai.use(chaiExclude);
chai.use(chaiAsPromised);
const {expect} = chai;

it("chai-exclude-promised-v1", ()=>{
    return expect(Promise.resolve({ a: 'a', b: 'b' })).excluding('a').to.eventually.deep.equal({ b: 'b' });
});

it("chai-exclude-promised-v2", ()=>{
    return expect(Promise.resolve({ a: 'a', b: 'b' })).to.eventually.excluding('a').deep.equal({ b: 'b' });
});
```
I'm using:

nodejs: **8.9.0**
mocha: **4.0.1**
chai: **4.1.2**
chai-as-promised: **7.1.1**
chai-exclude: **1.0.3**

**Comment by djalexd** [comment]
I'm trying to figure out the exact same use-case. Did you manage to find a solution?

**Comment by djalexd** [comment]
In my case the error is pretty self-explanatory:
`AssertionError: object tested must be an array, or an object, but promise given`
But I haven't got a clue how to fix this myself

**Comment by 95gabor** [comment]
The issue is still there. I couldn't find the solution yet. 😕

**Comment by meeber** [comment]
This work for me:

```js
const {use, expect} = require("chai");
use(require("chai-exclude"));
use(require("chai-as-promised"));

it("testing", function () {
  return expect(Promise.resolve({a: 1, b: 2})).to.eventually.excluding('a').deep.equal({b: 2});
});
```

Package.json:

```js
  "dependencies": {
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "chai-exclude": "^1.0.7",
    "mocha": "^4.1.0"
  }
```

**Comment by djalexd** [comment]
@95gabor @meeber order of plugin installation is important ... when I switched order it worked :)
thanks for help!
