### ISSUE TITLE
Why not provide a browserified equivalent with the library?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [domenic/chai-as-promised#234]
Spinning off of issues like #199 and #209: it's been mentioned many times that chai-as-promised is only meant to be used in CommonJS environments, and that users should use browserify/rollup/webpack/etc. to make browser-compatible versions.

...but why not provide a "catch-all" equivalent for AMD/browsers with the distribution? I'd be happy to send a PR adding it to the build & distribution.

**Comment by domenic** [comment]
I'd rather leave this up to consumers, who can use their favorite technology. The burden should be on them to adapt this to their app, not on me to maintain it.
