### ISSUE TITLE
eventually.throws / doesNotThrow

### ISSUE THREAD

**Issue by stanhuff** [domenic/chai-as-promised#237]
It's not clear to me how eventually.throws(fn) and eventually.doesNotThrow(fn) translate into chai-as-promised.  In the code below, "test1" passes as expected for me and "test2" results in an error from chai-as-promised itself:

TypeError: promise.then is not a function
      at Object.assert.eventually.(anonymous function) [as doesNotThrow] (node_modules/chai-as-promised/lib/chai-as-promised.js:343:45)

Are throws() and doesNotThrow() unsupported or do I need to use a different syntax in this case? Relevant package versions are listed below also.

Thanks!

```
const chai = require("chai");
const assert = chai.assert;
const chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);

suite("suite", () => {

    function f() {
        return Promise.resolve();
    }

    test("test1", () => {
        return assert.isFulfilled(f());
    });

    test("test2", () => {
        return assert.eventually.doesNotThrow(() => f());
    });
});
```
node: 9.3.0
mocha: 4.0.1
chai: 4.1.2
chai-as-promised: 7.1.1

**Comment by domenic** [comment]
They work on promises for functions. This is very rare, but is completely symmetric with all other "eventually" asserters.

**Comment by stanhuff** [comment]
Agreed.  It is completely symmetric.  I suppose I was expecting to find the analog to the normal throws/doesNotThrow for async functions.  Passing an async function to the normal throws doesn't work as hoped either.  An alternative/work-around is to execute the async function outside the context of the chai assert and then pass in the resulting promise to isRejected/isFullfilled, but technically an async'ish function could throw during its initial "step" instead of returning the promise and the code that orchestrates that otherwise simple test is clumsy.  Even if the async function doesn't throw, that alternaitve requires more syntax to execute it outside the assertion context, which isn't analogous to the normal throws/doesNotThrow pattern.

Is there a different API that provides the analog to throws/doesNotThrow for async functions?

**Comment by domenic** [comment]
There is isRejected/isFulfilled. There is no API that works for a function that could both throw and return a rejected promise; such functions are poorly coded and not something this library is meant to help test.

**Comment by stanhuff** [comment]
Agreed about the "poorly" coded.  It's simply a conceptual leak.  Nonetheless, invoking an async function separately and passing in the resulting promise to a different function seems less intuitive for the 80% case when one is familiar with calling throws/etc for testing failure results of functions.  Some things can have multiple axes of symmetry.  But this is just a matter of preference.  I'll write a helper function. 
Thanks!
