### ISSUE TITLE
array include checks don't work as expected

### ISSUE THREAD

**Issue by scorpiodawg** [domenic/chai-as-promised#242]
Hello there,

I'm using c-a-p with mocha/sinon. I have some methods returning promises that resolve to arrays of objects. It appears the "includes" behavior supported by chai in their documentation doesn't work with c-a-p. Am I doing something wrong?

The example on the chai website says this ([here](http://www.chaijs.com/api/bdd/#method_include)):

`expect({a: 1, b: 2, c: 3}).to.include({a: 1, b: 2});`

However, when I have chai `use` chai-as-promised, the following:

`expect(Promise.resolve([{a: 1}])).to.eventually.be.an('array').to.include({a: 1})`

results in

```
(node:5639) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): AssertionError: expected [ {} ] to include {}
```

Is this a bug?

**Comment by domenic** [comment]
Your two assertions are not analogous. What happens when you change the first one to include array-testing as well?

**Comment by scorpiodawg** [comment]
Ack, sorry @domenic didn't realize my chai example was not using arrays. When I do that, that fails too:

```
> expect([{a: 1, b: 2, c: 3}]).to.include({a: 1, b: 2});

AssertionError: expected [ { a: 1, b: 2, c: 3 } ] to include { a: 1, b: 2 }
    at repl:1:33
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
    at emitOne (events.js:121:20)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
    at REPLServer.Interface._line (readline.js:631:8)
```

Is this a Chai issue you'd say?

**Comment by scorpiodawg** [comment]
Looks like I need a `deepEql`: https://stackoverflow.com/a/49540331/562139
