### ISSUE TITLE
Incompatible with IE 11

### ISSUE THREAD

**Issue by leoselig** [domenic/chai-as-promised#243]
In commit 16dde11e8d566771681dd6c39fd28716c9de69fa arrow function syntax has been introduced at several places causing our test suites to break on IE 11 after update. I understand from the commit message that the goal was

>Start enforcing the use of newer syntax (as long as it's Node v4 compatible)

As logical as that seems, the chai eco system seems to be commited to supporting IE 11 (at least for now since it still plays an unfortunately big role). This change forces us to setup babel for `chai-as-promised` which violate typical practices.

I understand either way you are going but I'd love to have a commitment of this library to IE 11 support.

**Comment by domenic** [comment]
Thanks for the notice. I don't know anything about the "chai eco system", but for this library I'll be supporting Node v4 and above. You can use tools to convert it into something compatible with other systems. See https://github.com/domenic/chai-as-promised#browsernode-compatibility

**Comment by leoselig** [comment]
Thank you for the quick response!
When I wrote "chai eco system" I was a bit lazy. I was referring to
- [chai itself](https://github.com/chaijs/chai) being tested in all major browsers (including IE 11)
- [chai-enzyme](https://github.com/producthunt/chai-enzyme) which compiles down to ES2015 (hence, at least being commited to synatactically supporting IE 11 as well)

I admittedly overlooked this:
>If your browser doesn't support modern JavaScript syntax, you'll need to transpile it down using a tool like Babel.

Would you be up to accept a PR to add transpilation down to ES2015 via babel?

**Comment by domenic** [comment]
No, that's up to individual application authors, and not something I want to maintain in my repository.
