### ISSUE TITLE
Chai functions that take functions themselves are broken

### ISSUE THREAD

**Issue by ViKomprenas** [domenic/chai-as-promised#248]
For example:

```javascript
chai.assert.throws(function() { throw new Error(); }) // OK
chai.assert.eventually.throws(Promise.reject(new Error())) // fails, since it expects a promise for a function that will throw, not a promise that will throw
```

Workaround: use `isRejected`. Arguably, that's more natural with promises, but it's certainly not with `async`/`await`.

**Comment by domenic** [comment]
This is working as intended.

**Comment by domenic** [comment]
The latter is the intent.

**Comment by ViKomprenas** [comment]
I'm sorry, but what? What? I think you're misunderstanding me here. Either

- you created a library to make Chai able to take a promise for its first argument instead of the argument itself **because you wanted to be able to test promise-heavy software with Chai easier**, or
- you created a library to make Chai able to take a promise for its first argument instead of the argument itself **because it was something to do**.

If it's the former, then excessive focus on the means is costing you the goal; I genuinely cannot imagine it being the latter.

**Comment by domenic** [comment]
The intent is a straightforward translation of the asserters to act on promises. Asserters that act on functions (like "throws") now act on promises for functions, just like asserters for numbers now act on promises for numbers.
