### ISSUE TITLE
Is there any support for unhandled rejections?

### ISSUE THREAD

**Issue by inf3rno** [domenic/chai-as-promised#252]
I have a test something like this:

    it ("x", async function (){
        const a = await x.b();
        x.c();
    });

The c() does not return anything, but its side effect is an unhandled rejection, and that's what I expect in this scenario. So I need something like "expect c to result an unhandled rejection in 200 msecs". Is this supported by this lib, or should I write for myself?

**Comment by inf3rno** [comment]
Hmm I think I should have some sort of error handling interface on x, so I would not have to rely on unhandled rejections and I could suppress any kind of error if I want to. So I could do something like:

```js
it ("x", async function (){
    const a = await x.b();
    x.c(); // calls x.throw(e), which can be caught by x.catch()
    const e = await Promise.race([x.catch(), defer(200)]);
    expect(e instanceof MyError).to.equal(true);
});
```

**Comment by RobinKnipe** [comment]
Just a general point about javascript functions: if a function doesn't explicitly declare a return, it will still return after all lines have been evaluated, so in your first example above, both the anonymous function (2nd param of `it`) and `c` will return `undefined` (assuming no error is thrown or runtime exception occurs).
This means you can, for example:
```js
expect(x.c()).to.be.undefined
```
That aside, you should be able to wrap `x.c()` in a promise, which you can return to the test, then you can do:
```js
return expect(new Promise(function (res, rej) {
  res(
    x.c() // if this causes an error
  )
})).to.be.rejected // or rejectedWith(MyError)
```
