### ISSUE TITLE
expect(...).to.be.rejected always passes

### ISSUE THREAD

**Issue by septagram** [domenic/chai-as-promised#262]
The following test passes perfectly fine for me:
```
describe ('Simplest possible test', () => {
  it ('should not pass', () => {
    expect (Promise.resolve()).to.be.rejected
    expect (Promise.reject (new Error ('only one of those can pass, right?'))).to.be.rejected
  })
})
```
I'm confused. Chai-as-promised happily confirms that the promise is rejected even when it's actually resolved.

Here are the packages I'm using:
```
    "karma": "^4.4.1",
    "karma-mocha": "^1.3.0",
    "mocha": "^5.2.0",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
```

**Comment by jneander** [comment]
For expectations on a promise, the expectation itself becomes asynchronous. You need to tell the test to wait for the expectation to resolve. You can do this a few different ways.

```
describe('promise assertions', () => {
  it('asserts on a fulfilled promise', async () => {
    // Use async/await
    await expect(Promise.resolve()).to.be.fulfilled
  })

  it('asserts on a rejected promise', () => {
    // Return the promise, which the test will hook into using `.then()` and `.catch()`
    return expect(Promise.reject()).to.be.rejected
  })
})
```

Depending on your test framework, there might be an `assert` object passed into the test handler that you can call a method like `.done()` on. But the two versions above are more concise.

**Comment by septagram** [comment]
Oooh, thanks for the answer, I missed that critical piece of information when I was skimming through the docs. I now see that it's explicitly mentioned (it would be nice to also mention `await` as a valid approach in the docs, but it is obvious).

Going back to Chai as Promised as soon as I need to assert on a promise.
