### ISSUE TITLE
isRejected not behaving as assert.throw

### ISSUE THREAD

**Issue by liebrand** [domenic/chai-as-promised#47]
assert.throw accepts a string/regex to compare against the thrown error.message

eg:
      assert.throw(function() {
        throw new Error('error message');
      }, 'this is not the error message', 'my msg');

fails with:
AssertionError: expected [Function] to throw error including 'this is not the error message' but got 'error message'

but:
      var promise = new Promise(function(resolve, reject) {
        reject(new Error('error message'));
      });
      return assert.isRejected(promise, 'this is not the error message', "optional msg");

does not fail

**Comment by vikki** [comment]
Hi @domenic, @logicalparadox - I had a go at refactoring out checkError from assertions into its own utility. Its not quite finished (needs some more tests and improved docs on the checkError utility) but I wanted to see if you might take something like this, or if another approach would be better etc. etc. ?
Chai is at https://github.com/vikki/chai/tree/addCheckError and chai-as-promised at https://github.com/vikki/chai-as-promised/tree/useCheckError

**Comment by keithamus** [comment]
@vikki you should submit this as a Pull Request to chai's repo, and we can get the ball rolling on implementing this proper :smile:.

**Comment by domenic** [comment]
I'm rolling up all bugs in the category "isRejected/rejectedWith doesn't behave like Chai's error rejectors" into #166.

**Comment by JustinLivi** [comment]
Hi all! I'm excited about the direction that you're taking chai and chai-as-promised with breaking error checking out into a more modular system. I'm just wondering where the best place to track progress on this would be? I wasn't able to locate the appropriate issue in the chai.js repo. Would this be the best issue to subscribe to? Thanks!

**Comment by meeber** [comment]
@JustinLivi The relevant repo is here: https://github.com/chaijs/check-error

It'll be included in the upcoming Chai v4 alpha release which will be available via npm. 

Right now the check-error module only contains helper functions used by Chai's `throw` assertion. In the future, it's possible more logic will be moved into it from Chai.

**Comment by JustinLivi** [comment]
@meeber Great! Thanks so much
