### ISSUE TITLE
Assertion does not fail if promise is rejected without reason

### ISSUE THREAD

**Issue by tidlund** [domenic/chai-as-promised#56]
In the following code, the two test cases should fail. However, they pass.

    var chai = require('chai');
    var chaiAsPromised = require('chai-as-promised');
    chai.use(chaiAsPromised);
    var assert = chai.assert;
    var Q = require('q');
    
    describe('Chai-test', function () {

      it('Should fail if rejected with no value ', function () {
        var promise = Q.reject();
        return assert.becomes(promise,2);
      });

      it('Should fail if rejected with no value (eventually.equal)', function () {
        var promise = Q.reject();
        return assert.eventually.equal(promise,2);
      });
    });

**Comment by domenic** [comment]
I'm rolling up all bugs in the category "isRejected/rejectedWith doesn't behave like Chai's error rejectors" into #166.
