### ISSUE TITLE
`rejectedWith` not reading constructor names

### ISSUE THREAD

**Issue by OliverJAsh** [domenic/chai-as-promised#64]
With plain Chai, if I do:

``` js
expect(function () {
    throw new Error();
}).to.throw(Array);
```

I get:

```
AssertionError: expected [Function] to throw 'Array' but 'Error' was thrown
```

With Chai as Promised, if I do the equivalent:

``` js
var d = Q.defer();
d.reject(new Error());
return expect(d.promise).to.eventually.be.rejectedWith(Array);
```

I get:

```
AssertionError: expected promise to be rejected with undefined but it was rejected with [Error]
```

Chai as Promised thinks that the `Array` constructor’s name is `undefined`.

I had a brief look into this: https://github.com/domenic/chai-as-promised/blob/d607a914ea8cff473f179becf8029a241ed011ee/lib/chai-as-promised.js#L152. Should we be reading the name property from the constructor function, instead of creating an instance and looking for a name on that? Alternatively the name could be read as `instance.constructor.name`. Here is what looks like the equivalent line but in Chai: https://github.com/chaijs/chai/blob/ab999d89171634e3b953765c6d0c8a7d454a4b59/lib/chai/core/assertions.js#L1054

Also, the error message format is slightly difference compared to standard Chai. Is this intentional, out of curiosity?

**Comment by domenic** [comment]
I'm rolling up all bugs in the category "isRejected/rejectedWith doesn't behave like Chai's error rejectors" into #166.
