### ISSUE TITLE
PhantomJS

### ISSUE THREAD

**Issue by gogoyqj** [domenic/chai-as-promised#77]
why PhantomJS is not compatible

**Comment by scottohara** [comment]
@gogoyqj  PhantomJS 1.x was built on QtWebkit. This is a very old version of WebKit, and its JS support is severely lacking in modern features (no function.bind() support for example). Many tools and libraries don't work with phantom for this reason.

PhantomJS 2.x is only now becoming available (although some platforms are not yet fully supported), which is based on a more current version of WebKit.

I would presume that this is the (or a prime) reason why chai-as-promised has never supported PhantomJS, but I would hope that as the 2.x version matures and becomes common place that we might see support in chai-as-promised.

**Comment by domenic** [comment]
Somehow missed this the first time, thanks @scottohara for explaining.
