### ISSUE TITLE
`rejected` rejects if returned reason is a rejecting thenable

### ISSUE THREAD

**Issue by Steditor** [domenic/chai-as-promised#79]
jQuery's `$.ajax` and its equivalents return a non-Promise-standard deferrable that still can be used with Promises via `Promise.resolve()` of the ECMAScript 6 promises due to being thenable.

If you want to test such a Promise with `.rejected`, chai-as-promised will return the reason to allow further assertions and transform the Promise into a fulfillment (as stated in [the rejected property](https://github.com/domenic/chai-as-promised/blob/master/lib/chai-as-promised.js#L131-132)). The problem is, that if you return a thenable from a Promise, it will again be resolved as a Promise, which leads to a rejecting assertion instead of a resolving one:
```javascript
promise = Promise.resolve($.get(...))
return expect(promise).to.be.rejected // the assertion will be true, but the returned Promise rejects anyway
```
whereas
```javascript
promise = Promise.resolve($.get(...))
return expect(promise).not.to.be.fulfilled // the assertion will be true, and the returned Promise fulfills
```
works - which i think is counterintuitive.
Is this a bug of chai-as-promised, or is there another way I am supposed to test those ajax-requests?

**Comment by domenic** [comment]
> The problem is, that if you return a thenable from a Promise, it will again be resolved as a Promise

I don't see this happening in your example. Can you explain?

**Comment by domenic** [comment]
Oh, I see, the problem is that jQXHR's reject with themselves. Oh dear.

**Comment by Steditor** [comment]
Exactly. That is awful, but is their current implementation...

**Comment by domenic** [comment]
I think you would be better off wrapping up $.get() into something sane, e.g.

```js
function getButNotInsane(...args) {
  return Promise.resolve($.get(...args)).catch(jqXHR => {
    throw new Error("Bad stuff happened!");
  });
}
```

(You could of course make the rejection more informative, see e.g. [this old Q adapter I made](https://github.com/domenic/client-side-packages-demo/blob/d75198a51d9b1644bea8329030180dc59b12669d/lib/github.js#L7-L30).)

In general I agree this is kind of annoying as normally with Promises/A+ you can reject with a thenable and nothing weird happens. So Chai as Promised is making an additional assumption here. I will leave this open to see if I can think of a workaround. E.g. maybe I can wrap things into a wrapper object and then unwrap them later. If nothing else I will need to add a note in the readme about this limitation.

**Comment by Steditor** [comment]
Great, thank you! For now everything works for me with workarounds: `not.to.be.fulfilled` works fine to check if the Promise rejects, and I'm doing all other tests on the object provided by `prom.catch` (as `eventually` suffers from the same problem)

And maybe it really is the best idea to wrap all the application's jQuery-requests into a sanitizer...

**Comment by domenic** [comment]
I'm rolling up all bugs in the category "isRejected/rejectedWith doesn't behave like Chai's error rejectors" into #166.
