### ISSUE TITLE
.property(key, prop) not working properly on mongoDB ObjectID's 

### ISSUE THREAD

**Issue by sertugkaya** [domenic/chai-as-promised#80]
When I try: 
`myPromise.should.eventually.to.have.deep.property("actionBy", client._id),`
I get:
> expected { Object (__parentArray, __parent, ...) } to have a deep property 'actionBy' of 54da097089c61a052a2b1d79, but got 54da097089c61a052a2b1d79

But trying it using `equals()` like this works:
`myPromise.should.eventually.to.have.deep.property("actionBy").equals(client._id),`
Using toString() on ID's does not change the result.

**Comment by domenic** [comment]
Can you create a code sample I can run on my own system and test?

**Comment by manast** [comment]
+1 it is really easy to reproduce, It would be great to get fixed :).

**Comment by domenic** [comment]
If it is easy to reproduce,  then please product the sample code I asked for above.

**Comment by manast** [comment]
Ok, I realized this is wrong repo, I thought this was chai main repo... anyway an example:
```
var mongoose = require('mongoose');
var obj = {
  a : mongoose.Types.ObjectId("557edb4d82aff15704f433df");
};
expect(obj).to.have.property('a', mongoose.Types.ObjectId("557edb4d82aff15704f433df"));
```

I am currently using chaid and is solving my problem like this:
```
expect(obj).to.have.property('a').to.be.id(mongoose.Types.ObjectId("557edb4d82aff15704f433df"));
```
