### ISSUE TITLE
Assertion always pass, no matter promise result

### ISSUE THREAD

**Issue by endorama** [domenic/chai-as-promised#84]
Hello, thanks for this library!

I'm stuck in trying to make chai-as-promised work. For some reason tests always pass or always fail, regardless promise result.

"promised" code:
```javascript
function loadFile (filePath) {
    var deferred = Q.defer();
    deferred.reject(new Error('Some error'));
    return deferred.promise;
}
```

Test code:
```javascript
it('should permit comments in project file', function() {
    return loadFile(projectFile).should.be.ok;
});
```

This test always pass, while is obvious that the promise is being rejected. What am I missing?
I read about issue #56 but this doesn't seem the case ( or is it?? ) as I'm rejecting with a proper Error.

If I change the code to use `eventually`:
```javascript
it('should permit comments in project file', function() {
    return loadFile(projectFile).should.eventually.be.ok;
});
```
the test fails, but if I update the code to resolve the promise:
```javascript
function loadFile (filePath) {
    var deferred = Q.defer();
    deferred.resolve('foobar');
    return deferred.promise;
}
```
the test now always fails...

Any help is appreciated :)

**Comment by domenic** [comment]
> return loadFile(projectFile).should.be.ok;

You are not using Chai as Promised here at all. You are using just plain Chai. `.should.be.ok` tests if the object is truthy. All promises are objects, and so are automatically truthy.

> return loadFile(projectFile).should.eventually.be.ok;

this should work. Can you produce a complete example file I can run, unmodified, in Mocha that demonstrates the problem?

**Comment by endorama** [comment]
> You are not using Chai as Promised here at all. You are using just plain Chai. .should.be.ok tests if the  object is truthy. All promises are objects, and so are automatically truthy.

This clarifies a lot the use of `eventually` ( I misunderstood the Readme ).

Cleaning up my code to create a valid example file I found the error that confused me in the beginning, and was a simple typo ( a `P` of `p` in one of the test cases, that obviously was always failing :( )

Thanks for the help! Everything is working great now. Closing

**Comment by domenic** [comment]
Awesome. If you can think of ways to clarify the readme, feel free to send a pull request.
