### ISSUE TITLE
AssertionError: expected { state: 'pending' } to equal ...

### ISSUE THREAD

**Issue by OKNoah** [domenic/chai-as-promised#86]
var chai = require( 'chai' ),
		chaiAsPromised = require( 'chai-as-promised' ),
		assert = require( 'chai' ).assert,
		should = require( 'chai' ).should(),
		getUser = require( 'helpers/get-user' )

	describe( 'GetUser', function () {

		describe( "Get a user's ID", function() {

			it( "return a user's ID when given token", function( done ) {
				this.timeout( 4000 )

				var token = "BIG-STRING"

				return getUser( token ).should.eventually.equal( "ANOTHER-STRING" )
			})

		})

	})

This gives the error `AssertionError: expected { state: 'pending' } to equal 'ANOTHER-STRING'`. Am I doing that right?

**Comment by domenic** [comment]
Your `done` argument signals to Mocha that this is not a promise-related test. You need to remove that.

**Comment by OKNoah** [comment]
Now it just times out.

**Comment by OKNoah** [comment]
Here's a Stackoverflow question: http://stackoverflow.com/questions/28705050/mocha-and-chai-as-promised-time-out

**Comment by domenic** [comment]
That likely means getUser(token) never fulfills or rejects.

It would be best if you could create a small repro case I could run on my own system in order to debug.

**Comment by OKNoah** [comment]
Does the SO link have enough details for you? Weird that it works in the app but not in the test.

**Comment by domenic** [comment]
It doesn't, because `'../models/userModel'` doesn't exist on my computer. I need an example that I can run.

**Comment by OKNoah** [comment]
'use strict';

	var mongoose = require( 'mongoose-q' )( require( 'mongoose' ) ),
		bcrypt = require('bcrypt-nodejs')

	var UserSchema = new mongoose.Schema({
		username: {
			type: String,
			required: true,
			unique: true
		},
		password: {
			type: String,
			required: true
		},
		email: {
			type: String,
			required: true,
			unique: true
		},
		joined: Number,
		token: String
	})

	module.exports = mongoose.model( 'User', UserSchema )

If this enough or do you want a `.zip` or something?

**Comment by domenic** [comment]
And that will work without me having Mongo installed on my system?

**Comment by OKNoah** [comment]
Sorry, I'm not sure. I assume you need Mongo.

**Comment by domenic** [comment]
Ok. Can you try to produce an example that doesn't involve Mongo or Mongoose or similar? That way we can find out if it's a problem with Chai as Promised or a problem with those modules.
________________________________

**Comment by OKNoah** [comment]
I've only ever used Mongo/Mongoose. I'll try come up with something later.

**Comment by OKNoah** [comment]
I tried replacing all the code in `get-user.js`, inside the `return Q.Promise( ... )` part with a simple `if` statement and `resolve` and that worked. No time out. Not sure if that helps.

**Comment by OKNoah** [comment]
I accidentally fixed this by adding

    app = require( 'server.js' )

which I guess runs the server when the test runs.

**Comment by domenic** [comment]
Hah! That makes sense, why the promise would stay forever-pending without that. Yay!
