### ISSUE TITLE
how to make multiple assertion using assert style

### ISSUE THREAD

**Issue by neekey** [domenic/chai-as-promised#88]
Guys, I looked through all the examples in the documentation, and each of them included only one assertion, like below:

```js
it( 'test with promise', function(){
    return assert.becomes(promise, "foo", "optional message");
});
```

what if I want to put more than one assertions in it like below:

```js
var newUser = { name: 'neekey', age: 12 };
var user = createUser( newUser ); // return a promise

// and I want to check if the user created gets the same attributes as the `newUser`, 
// I need to use assert sentence multiple times:

assert.eventually.propertyVal(user, 'name', newUser.name );
assert.eventually.propertyVal(user, 'age', newUser.age );
```

**Comment by domenic** [comment]
Under "Another example of where this can be useful is when performing assertions on multiple promises:" in the readme.

**Comment by chadananda** [comment]
What? I have the same question. How to apply multiple assertions for one promise. All I see in the README is multiple promises with one assertion each.

**Comment by domenic** [comment]
You can use the same promise variable in those assertions, thus applying multiple assertions to the same promise.
