### ISSUE TITLE
Negation not working

### ISSUE THREAD

**Issue by Robinfr** [domenic/chai-as-promised#89]
There does not seem be a way to use the ``.not`` chain. This makes it very hard to test certain things in my case.

**Comment by domenic** [comment]
It works in the tests, as you can see. Please provide an example.
________________________________

**Comment by Robinfr** [comment]
Well my case had to do with a Promise returning a string:

``getTitle().should.eventually.not.become('Test')

This would give me the error that not is a string or something similar.

**Comment by domenic** [comment]
Can you put together a complete example I can run on my computer, with no dependencies besides Chai as Promised and your test runner (Mocha or something similar)?

**Comment by Robinfr** [comment]
Hmm, I can, but I'm not sure how you'd want this delivered?

**Comment by domenic** [comment]
A 10-20 line sample should be pastable into this GitHub issue.

**Comment by jxm262** [comment]
I'm having the same issue.  Here's a quick example -   
  
    var cache = require("../../../api/lib/persistent-data")
    , chai = require('chai')
    , should = chai.should()
    , chai_as_promised = require('chai-as-promised')
    , Promise = require('bluebird');

    chai.use(chai_as_promised);

    describe('api.js', function() {

    describe('get function', function(){

        it('should be rejected if key not found', function(){
            cache.get('my_key').should.be.rejectedWith(false);
        });

        it('should not be rejected if key exists', function(){
            cache.set('my_key', 'my_value');
            cache.get('my_key').should.eventually.equal('my_valddue');
        });

    });
    });

    //implementation
  
    var Promise = require('bluebird');
    var data = {};

    module.exports = {

    set: function (k, v) {
        data[k] = v;
    },

    get: function (k) {
        return new Promise(function (fullfill, reject) {
            (typeof data[k] !== "undefined") ? fullfill(data[k]) : reject(false);
        });
    },

    unset: function (k) {
        delete data[k];
    }

};

**Comment by jxm262** [comment]
Here's the output of the test.  It shows the Assertion Error , but the mocha test never actually fails.  
  
![image](https://cloud.githubusercontent.com/assets/3460750/6536894/8416f12c-c41f-11e4-9f6e-0257459e7adb.png)

**Comment by jxm262** [comment]
Also, if I run it with this line , the same will happen.  An assertion error , but the test still shows as passed in Mocha.

    cache.get('my_key').should.eventually.equal('some_other_value');

**Comment by jxm262** [comment]
![image](https://cloud.githubusercontent.com/assets/3460750/6536942/e25c79b4-c41f-11e4-9b3c-0f70e52e86ee.png)

**Comment by domenic** [comment]
@jxm262 you are not returning your promises from your Mocha tests; see the readme.

**Comment by jxm262** [comment]
Ahh, many apologies if that was the issue :(   ill try it out tonight when i get home.

**Comment by Robinfr** [comment]
I've actually figured out my issue was with WebdriverIO, so this can be closed.
