### ISSUE TITLE
`Resolved` alias

### ISSUE THREAD

**Issue by demisx** [domenic/chai-as-promised#91]
Hi. Is there an existing way to test for `resolved` instead of `fulfilled`? Basically, I'd like to be able to do this to be consistent with the language other promises use in our app (i.e. resolved/rejected):

```js
expect(promise).to.not.be.resolved;
expect(promise).to.not.be.resolvedWith(...);
```

Thank you.

**Comment by domenic** [comment]
Resolved does *not* mean the same thing as fulfilled... https://github.com/domenic/promises-unwrapping/blob/master/docs/states-and-fates.md

**Comment by demisx** [comment]
Sorry, didn't realize those were different concepts. Thank you for sharing the reading material.

**Comment by demisx** [comment]
Though I still have hard time understanding this line  from https://github.com/domenic/promises-unwrapping:

>A resolved promise may be pending, fulfilled, or rejected.

I thought if a promise is in pending state, then it is unresolved.

**Comment by domenic** [comment]
Yes, pending implies unresolved. But unresolved does not imply pending. (Being a hamster implies being a mammal. But being a mammal does not imply being a hamster.)

**Comment by demisx** [comment]
A-ha. The hamster analogy really helps! :+1: If I understand correctly, a promise resolved with a promise would be still in a `pending` state.

**Comment by domenic** [comment]
Well, a promise resolved with a _pending_ promise would still be in a pending state :). A promise resolved with a rejected promise would be in a rejected state. Etc.

**Comment by demisx** [comment]
Yeah, I know. One would think it should be simpler to digest. :) I've gone ahead and created a diagram (it's editable) to visually present the concepts you outline on that page. I am gonna frame it and put it on my wall. https://docs.google.com/drawings/d/1mv6tFSTJoHS7DtT3UBlFaTow2-qI9jJyCn6HSKFPqb4/edit?usp=sharing

Feel free to comment/edit. I don't mind sharing it with the community, since there are so much confusion about this.

**Comment by domenic** [comment]
Awesome! I made some minor edits, changing the arrows (which to me implied causation) into just lines (implying some sort of "linkage"). And also adding dashed arrows for the possible transitions that are allowed. Feel free to take or leave them, just suggestions.

**Comment by demisx** [comment]
That's a bunch of lines! :) JK. This makes more sense now. I'll just add some annotations in the legend to tell what those lines are. Thank you for being so cool about this.
