### ISSUE TITLE
Compatibility with chai-spies

### ISSUE THREAD

**Issue by Ryckes** [domenic/chai-as-promised#93]
I am not really sure about in which of the two repositories I should post this issue, but I found that if I use at the same time chai-spies and chai-as-promised, depending on the order of the calls to chai.use() I may or may not use chai-spies. The following code won't work correctly, but if you change the order of chai.use() calls it will work again:
```
var chai = require('chai'),
    expect = chai.expect,
    should = chai.should(),
    spies = require('chai-spies'),
    chaiAsPromised = require('chai-as-promised'),
    Promise = require('bluebird');

// Change order of those two for spies to work:
chai.use(spies);
chai.use(chaiAsPromised);

describe('test', function() {
    it('should fail', function() {
        var spy = chai.spy();
        // Will fail because called is not a function
        expect(spy).to.have.been.called();
    });

    it('should succeed', function() {
        var promise = Promise.resolve(true);
        // Always works as expected
        promise.should.become(true);
    });
});
```

I don't know if I am doing everything right there. If it is an issue of chai-spies, please let me know and I'll post the issue there. If it is an issue of my code, my apologies.

**Comment by domenic** [comment]
Chai as Promised does some weird stuff, indeed, so I could believe this is our fault. If you have any bandwidth to try to dig and find out what's wrong, that'd be much appreciated. Kind of a wild guess, but #87 might be helpful as it's also about inter-library compatibility (but I can't land it without some tests :()

**Comment by Ryckes** [comment]
I have checked out that PR and I've found out that it does fix the issue. I don't know how to turn that into tests though :/ I guess that some kind of independent tests, where a chainable method is added, and then chai.use(chaiAsPromised) is executed, could test if the chainable method is still usable somehow.

The thing is chai.use(chaiAsPromised) is executed before the tests in test/support/node.js, and I don't really know how to run completely independent tests in mocha (without running mocha twice).

**Comment by domenic** [comment]
Running Mocha twice is totally fine. Maybe add another folder called spies-integration-test or something and change `npm test` to `mocha && mocha spies-integration-test` or something like that.

**Comment by Ryckes** [comment]
I made the PR some days ago, any news on this? Something to improve?

**Comment by domenic** [comment]
Sorry, I've been traveling; will merge when I get the chance.
________________________________

**Comment by Ryckes** [comment]
There's no hurry, thank you for your answer :)

**Comment by domenic** [comment]
Fixed by #94.

**Comment by joshperry** [comment]
@Ryckes Thanks for doing this work. Your case is not one that I was targeting, and without looking at chai-spies I'm not sure why my change fixed this issue. For dirty-chai, I just needed to know when a plugin was adding a new chainable or modifying an existing one.

Out of curiosity, did the test at `chainable-methods.coffee:28` fail before applying my changes?

**Comment by Ryckes** [comment]
Yes! It did fail and now it passes :) I verified it. You can checkout a previous commit's chai-as-promised.js and run the tests.
